/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Robert Hurst
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_SystemSetup                         0
#define GD_TaxmanSetup                         1
#define GD_GangEditor                          2
#define GD_NewUserSetup                        3
#define GD_PlayerEditor                        4
#define GD_UserEditor                          5

#define GDX_SystemSetup                        0
#define GDX_TaxmanSetup                        1
#define GDX_GangEditor                         2
#define GDX_NewUserSetup                       3
#define GDX_PlayerEditor                       4
#define GDX_UserEditor                         5

#define GD_NUgold                              0
#define GD_NUbank                              1
#define GD_NUweapon                            2
#define GD_NUarmor                             3
#define GD_NUpost                              4
#define GD_NUupload                            5
#define GD_NUbyte                              6
#define GD_NUfileratio                         7
#define GD_NUbyteratio                         8

#define GDX_NUgold                             0
#define GDX_NUbank                             1
#define GDX_NUweapon                           2
#define GDX_NUarmor                            3
#define GDX_NUpost                             4
#define GDX_NUupload                           5
#define GDX_NUbyte                             6
#define GDX_NUfileratio                        7
#define GDX_NUbyteratio                        8

#define GD_IRSname                             0
#define GD_IRSmoney                            1
#define GD_IRSratio                            2

#define GDX_IRSname                            0
#define GDX_IRSmoney                           1
#define GDX_IRSratio                           2

#define GD_SYShandle                           0
#define GD_SYSname                             1
#define GD_SYSdate                             2
#define GD_SYScalls                            3
#define GD_SYSbest                             4

#define GDX_SYShandle                          0
#define GDX_SYSname                            1
#define GDX_SYSdate                            2
#define GDX_SYScalls                           3
#define GDX_SYSbest                            4

#define GD_GANGname                            0
#define GD_GANGleader                          1
#define GD_GANGmember2                         2
#define GD_GANGmember3                         3
#define GD_GANGmember4                         4
#define GD_GANGdelete                          5
#define GD_GANGhandle1                         6
#define GD_GANGhandle2                         7
#define GD_GANGhandle3                         8
#define GD_GANGhandle4                         9
#define GD_GANGnext                            10
#define GD_GANGprev                            11

#define GDX_GANGname                           0
#define GDX_GANGleader                         1
#define GDX_GANGmember2                        2
#define GDX_GANGmember3                        3
#define GDX_GANGmember4                        4
#define GDX_GANGdelete                         5
#define GDX_GANGhandle1                        6
#define GDX_GANGhandle2                        7
#define GDX_GANGhandle3                        8
#define GDX_GANGhandle4                        9
#define GDX_GANGnext                           10
#define GDX_GANGprev                           11

#define GD_PLAYERnext                          0
#define GD_PLAYERprev                          1
#define GD_PLAYERdelete                        2
#define GD_PLAYERhandle                        3
#define GD_PLAYERrealestatetext                4
#define GD_PLAYERsecuritytext                  5
#define GD_PLAYERstrsp                         6
#define GD_PLAYERintsp                         7
#define GD_PLAYERdexsp                         8
#define GD_PLAYERchasp                         9
#define GD_PLAYERshieldsp                      10
#define GD_PLAYERhonesp                        11
#define GD_PLAYERhealsp                        12
#define GD_PLAYERteleportsp                    13
#define GD_PLAYERblastsp                       14
#define GD_PLAYERressp                         15
#define GD_PLAYERconsp                         16
#define GD_PLAYERtrasp                         17
#define GD_PLAYERcuresp                        18
#define GD_PLAYERillsp                         19
#define GD_PLAYERdissp                         20
#define GD_PLAYERmorphsp                       21
#define GD_PLAYERp1                            22
#define GD_PLAYERp2                            23
#define GD_PLAYERp3                            24
#define GD_PLAYERp4                            25
#define GD_PLAYERp5                            26
#define GD_PLAYERp6                            27
#define GD_PLAYERp7                            28
#define GD_PLAYERp8                            29
#define GD_PLAYERp9                            30
#define GD_PLAYERp10                           31
#define GD_PLAYERp11                           32
#define GD_PLAYERp12                           33
#define GD_PLAYERp13                           34
#define GD_PLAYERp14                           35
#define GD_PLAYERp15                           36
#define GD_PLAYERp16                           37
#define GD_PLAYERnovice                        38
#define GD_PLAYERid                            39
#define GD_PLAYERgang                          40
#define GD_PLAYERlevel                         41
#define GD_PLAYERclass                         42
#define GD_PLAYERgender                        43
#define GD_PLAYERhp                            44
#define GD_PLAYERsp                            45
#define GD_PLAYERstr                           46
#define GD_PLAYERint                           47
#define GD_PLAYERdex                           48
#define GD_PLAYERcha                           49
#define GD_PLAYERstatus                        50
#define GD_PLAYERblessed                       51
#define GD_PLAYERcursed                        52
#define GD_PLAYERgold                          53
#define GD_PLAYERbank                          54
#define GD_PLAYERloan                          55
#define GD_PLAYERweapon                        56
#define GD_PLAYERwcmod                         57
#define GD_PLAYERarmor                         58
#define GD_PLAYERacmod                         59
#define GD_PLAYERrealestate                    60
#define GD_PLAYERsecurity                      61
#define GD_PLAYERhull                          62
#define GD_PLAYERcannon                        63
#define GD_PLAYERram                           64

#define GDX_PLAYERnext                         0
#define GDX_PLAYERprev                         1
#define GDX_PLAYERdelete                       2
#define GDX_PLAYERhandle                       3
#define GDX_PLAYERrealestatetext               4
#define GDX_PLAYERsecuritytext                 5
#define GDX_PLAYERstrsp                        6
#define GDX_PLAYERintsp                        7
#define GDX_PLAYERdexsp                        8
#define GDX_PLAYERchasp                        9
#define GDX_PLAYERshieldsp                     10
#define GDX_PLAYERhonesp                       11
#define GDX_PLAYERhealsp                       12
#define GDX_PLAYERteleportsp                   13
#define GDX_PLAYERblastsp                      14
#define GDX_PLAYERressp                        15
#define GDX_PLAYERconsp                        16
#define GDX_PLAYERtrasp                        17
#define GDX_PLAYERcuresp                       18
#define GDX_PLAYERillsp                        19
#define GDX_PLAYERdissp                        20
#define GDX_PLAYERmorphsp                      21
#define GDX_PLAYERp1                           22
#define GDX_PLAYERp2                           23
#define GDX_PLAYERp3                           24
#define GDX_PLAYERp4                           25
#define GDX_PLAYERp5                           26
#define GDX_PLAYERp6                           27
#define GDX_PLAYERp7                           28
#define GDX_PLAYERp8                           29
#define GDX_PLAYERp9                           30
#define GDX_PLAYERp10                          31
#define GDX_PLAYERp11                          32
#define GDX_PLAYERp12                          33
#define GDX_PLAYERp13                          34
#define GDX_PLAYERp14                          35
#define GDX_PLAYERp15                          36
#define GDX_PLAYERp16                          37
#define GDX_PLAYERnovice                       38
#define GDX_PLAYERid                           39
#define GDX_PLAYERgang                         40
#define GDX_PLAYERlevel                        41
#define GDX_PLAYERclass                        42
#define GDX_PLAYERgender                       43
#define GDX_PLAYERhp                           44
#define GDX_PLAYERsp                           45
#define GDX_PLAYERstr                          46
#define GDX_PLAYERint                          47
#define GDX_PLAYERdex                          48
#define GDX_PLAYERcha                          49
#define GDX_PLAYERstatus                       50
#define GDX_PLAYERblessed                      51
#define GDX_PLAYERcursed                       52
#define GDX_PLAYERgold                         53
#define GDX_PLAYERbank                         54
#define GDX_PLAYERloan                         55
#define GDX_PLAYERweapon                       56
#define GDX_PLAYERwcmod                        57
#define GDX_PLAYERarmor                        58
#define GDX_PLAYERacmod                        59
#define GDX_PLAYERrealestate                   60
#define GDX_PLAYERsecurity                     61
#define GDX_PLAYERhull                         62
#define GDX_PLAYERcannon                       63
#define GDX_PLAYERram                          64

#define GD_USERhandle                          0
#define GD_USERaccessname                      1
#define GD_USERdelete                          2
#define GD_USERmaxcalls                        3
#define GD_USERnext                            4
#define GD_USERprev                            5
#define GD_USERid                              6
#define GD_USERname                            7
#define GD_USERstreet                          8
#define GD_USERcity                            9
#define GD_USERstate                           10
#define GD_USERzip                             11
#define GD_USERvoice                           12
#define GD_USERdata                            13
#define GD_USERpassword                        14
#define GD_USERaccess                          15
#define GD_USERcreated                         16
#define GD_USERexpired                         17
#define GD_USERbirth                           18
#define GD_USERlaston                          19
#define GD_USERsex                             20
#define GD_USERtotalcalls                      21
#define GD_USERposts                           22
#define GD_USERcallstoday                      23
#define GD_USERuploads                         24
#define GD_USERdownloads                       25
#define GD_USERfileratio                       26
#define GD_USERupbyte                          27
#define GD_USERdownbyte                        28
#define GD_USERbyteratio                       29

#define GDX_USERhandle                         0
#define GDX_USERaccessname                     1
#define GDX_USERdelete                         2
#define GDX_USERmaxcalls                       3
#define GDX_USERnext                           4
#define GDX_USERprev                           5
#define GDX_USERid                             6
#define GDX_USERname                           7
#define GDX_USERstreet                         8
#define GDX_USERcity                           9
#define GDX_USERstate                          10
#define GDX_USERzip                            11
#define GDX_USERvoice                          12
#define GDX_USERdata                           13
#define GDX_USERpassword                       14
#define GDX_USERaccess                         15
#define GDX_USERcreated                        16
#define GDX_USERexpired                        17
#define GDX_USERbirth                          18
#define GDX_Gadget195                          19
#define GDX_USERsex                            20
#define GDX_USERtotalcalls                     21
#define GDX_USERposts                          22
#define GDX_USERcallstoday                     23
#define GDX_USERuploads                        24
#define GDX_USERdownloads                      25
#define GDX_USERfileratio                      26
#define GDX_USERupbyte                         27
#define GDX_USERdownbyte                       28
#define GDX_USERbyteratio                      29

#define System_Setup_CNT 5
#define Taxman_Setup_CNT 3
#define Gang_Editor_CNT 12
#define New_User_Setup_CNT 9
#define Player_Editor_CNT 65
#define User_Editor_CNT 30

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct IntuiMessage   MainMsg;
extern struct IntuiMessage   New_User_SetupMsg;
extern struct IntuiMessage   Taxman_SetupMsg;
extern struct IntuiMessage   System_SetupMsg;
extern struct IntuiMessage   Gang_EditorMsg;
extern struct IntuiMessage   Player_EditorMsg;
extern struct IntuiMessage   User_EditorMsg;

extern int NewUserSetupClicked( void );
extern int TaxmanSetupClicked( void );
extern int SystemSetupClicked( void );
extern int GangEditorClicked( void );
extern int PlayerEditorClicked( void );
extern int UserEditorClicked( void );
extern int NUgoldClicked( void );
extern int NUbankClicked( void );
extern int NUweaponClicked( void );
extern int NUarmorClicked( void );
extern int NUpostClicked( void );
extern int NUuploadClicked( void );
extern int NUbyteClicked( void );
extern int NUfileratioClicked( void );
extern int NUbyteratioClicked( void );
extern int IRSnameClicked( void );
extern int IRSmoneyClicked( void );
extern int IRSratioClicked( void );
extern int SYShandleClicked( void );
extern int SYSnameClicked( void );
extern int SYSdateClicked( void );
extern int SYScallsClicked( void );
extern int GANGnameClicked( void );
extern int GANGleaderClicked( void );
extern int GANGmember2Clicked( void );
extern int GANGmember3Clicked( void );
extern int GANGmember4Clicked( void );
extern int GANGdeleteClicked( void );
extern int GANGnextClicked( void );
extern int GANGprevClicked( void );
extern int PLAYERnextClicked( void );
extern int PLAYERprevClicked( void );
extern int PLAYERdeleteClicked( void );
extern int PLAYERstrspClicked( void );
extern int PLAYERintspClicked( void );
extern int PLAYERdexspClicked( void );
extern int PLAYERchaspClicked( void );
extern int PLAYERshieldspClicked( void );
extern int PLAYERhonespClicked( void );
extern int PLAYERhealspClicked( void );
extern int PLAYERteleportspClicked( void );
extern int PLAYERblastspClicked( void );
extern int PLAYERresspClicked( void );
extern int PLAYERconspClicked( void );
extern int PLAYERtraspClicked( void );
extern int PLAYERcurespClicked( void );
extern int PLAYERillspClicked( void );
extern int PLAYERmorphspClicked( void );
extern int PLAYERdisspClicked( void );
extern int PLAYERp1Clicked( void );
extern int PLAYERp2Clicked( void );
extern int PLAYERp3Clicked( void );
extern int PLAYERp4Clicked( void );
extern int PLAYERp5Clicked( void );
extern int PLAYERp6Clicked( void );
extern int PLAYERp7Clicked( void );
extern int PLAYERp8Clicked( void );
extern int PLAYERp9Clicked( void );
extern int PLAYERp10Clicked( void );
extern int PLAYERp11Clicked( void );
extern int PLAYERp12Clicked( void );
extern int PLAYERp13Clicked( void );
extern int PLAYERp14Clicked( void );
extern int PLAYERp15Clicked( void );
extern int PLAYERp16Clicked( void );
extern int PLAYERnoviceClicked( void );
extern int PLAYERidClicked( void );
extern int PLAYERgangClicked( void );
extern int PLAYERlevelClicked( void );
extern int PLAYERclassClicked( void );
extern int PLAYERgenderClicked( void );
extern int PLAYERhpClicked( void );
extern int PLAYERspClicked( void );
extern int PLAYERstrClicked( void );
extern int PLAYERintClicked( void );
extern int PLAYERdexClicked( void );
extern int PLAYERchaClicked( void );
extern int PLAYERstatusClicked( void );
extern int PLAYERblessedClicked( void );
extern int PLAYERcursedClicked( void );
extern int PLAYERgoldClicked( void );
extern int PLAYERbankClicked( void );
extern int PLAYERloanClicked( void );
extern int PLAYERweaponClicked( void );
extern int PLAYERwcmodClicked( void );
extern int PLAYERarmorClicked( void );
extern int PLAYERacmodClicked( void );
extern int PLAYERrealestateClicked( void );
extern int PLAYERsecurityClicked( void );
extern int PLAYERhullClicked( void );
extern int PLAYERcannonClicked( void );
extern int PLAYERramClicked( void );
extern int USERidClicked( void );
extern int USERnameClicked( void );
extern int USERstreetClicked( void );
extern int USERcityClicked( void );
extern int USERstateClicked( void );
extern int USERzipClicked( void );
extern int USERvoiceClicked( void );
extern int USERdataClicked( void );
extern int USERpasswordClicked( void );
extern int USERaccessClicked( void );
extern int USERcreatedClicked( void );
extern int USERexpiredClicked( void );
extern int USERbirthClicked( void );
extern int USERlastonClicked( void );
extern int USERsexClicked( void );
extern int USERtotalcallsClicked( void );
extern int USERpostsClicked( void );
extern int USERcallstodayClicked( void );
extern int USERuploadsClicked( void );
extern int USERdownloadsClicked( void );
extern int USERfileratioClicked( void );
extern int USERupbyteClicked( void );
extern int USERdownbyteClicked( void );
extern int USERbyteratioClicked( void );
extern int USERnextClicked( void );
extern int USERprevClicked( void );
extern int USERdeleteClicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleMainIDCMP( void );
extern int OpenMainWindow( void );
extern void CloseMainWindow( void );
extern int HandleSystem_SetupIDCMP( void );
extern int OpenSystem_SetupWindow( void );
extern void CloseSystem_SetupWindow( void );
extern int HandleTaxman_SetupIDCMP( void );
extern int OpenTaxman_SetupWindow( void );
extern void CloseTaxman_SetupWindow( void );
extern int HandleGang_EditorIDCMP( void );
extern int OpenGang_EditorWindow( void );
extern void CloseGang_EditorWindow( void );
extern int HandleNew_User_SetupIDCMP( void );
extern int OpenNew_User_SetupWindow( void );
extern void CloseNew_User_SetupWindow( void );
extern int HandlePlayer_EditorIDCMP( void );
extern int OpenPlayer_EditorWindow( void );
extern void ClosePlayer_EditorWindow( void );
extern int HandleUser_EditorIDCMP( void );
extern int OpenUser_EditorWindow( void );
extern void CloseUser_EditorWindow( void );
