/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Robert Hurst
 */

#include <proto/exec.h>
#include <proto/dos.h>
#include <proto/graphics.h>
#include <proto/intuition.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>
#include <pragmas/exec_pragmas.h>
#include <pragmas/intuition_pragmas.h>
#include <pragmas/gadtools_pragmas.h>
#include <pragmas/graphics_pragmas.h>
#include <pragmas/utility_pragmas.h>
#include <workbench/workbench.h>
#include <workbench/startup.h>
#include <ctype.h>
#include <dos.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

char __near *__procname="Sysop";
long __near __stack=4096;
long __near __priority=0;

typedef	ULONG	JDATE;
extern	char *__montbl[],*__daytbl[];

#include "/include/server.h"
struct RPGserver server,*response;
struct MsgPort *RPGport,*RPGreply;
struct ServerTable *ServerTable;
struct gang GANG;
struct user USER;
UBYTE EMAILpath[41],MSGpath[41],NOTESpath[41];

#include "/include/rpgbbs.h"
struct Library *RPGBase;
DOUBLE d;
JDATE Julian;
UBYTE Today[9],Time[7];
UBYTE dated[16],timed[8];

#define	IRS				ServerTable->IRS
#define	NEW				ServerTable->NEW
#define	SYS				ServerTable->SYS

#include "Sysop.h"

static struct Screen         *Scr = NULL;
static UBYTE                 *PubScreenName = "RPGBBS Deluxe";
static APTR                   VisualInfo = NULL;
static struct Window         *MainWnd = NULL;
static struct Window         *System_SetupWnd = NULL;
static struct Window         *Taxman_SetupWnd = NULL;
static struct Window         *Gang_EditorWnd = NULL;
static struct Window         *New_User_SetupWnd = NULL;
static struct Window         *Player_EditorWnd = NULL;
static struct Window         *User_EditorWnd = NULL;
static struct Gadget         *System_SetupGList = NULL;
static struct Gadget         *Taxman_SetupGList = NULL;
static struct Gadget         *Gang_EditorGList = NULL;
static struct Gadget         *New_User_SetupGList = NULL;
static struct Gadget         *Player_EditorGList = NULL;
static struct Gadget         *User_EditorGList = NULL;
struct IntuiMessage    MainMsg;
struct IntuiMessage    System_SetupMsg;
struct IntuiMessage    Taxman_SetupMsg;
struct IntuiMessage    Gang_EditorMsg;
struct IntuiMessage    New_User_SetupMsg;
struct IntuiMessage    Player_EditorMsg;
struct IntuiMessage    User_EditorMsg;
static struct Gadget         *System_SetupGadgets[System_Setup_CNT];
static struct Gadget         *Taxman_SetupGadgets[Taxman_Setup_CNT];
static struct Gadget         *Gang_EditorGadgets[Gang_Editor_CNT];
static struct Gadget         *New_User_SetupGadgets[New_User_Setup_CNT];
static struct Gadget         *Player_EditorGadgets[Player_Editor_CNT];
static struct Gadget         *User_EditorGadgets[User_Editor_CNT];
static UWORD                  MainLeft;
static UWORD                  MainTop;
static UWORD                  MainWidth = 136;
static UWORD                  MainHeight = 129;
static UWORD                  System_SetupLeft;
static UWORD                  System_SetupTop;
static UWORD                  System_SetupWidth = 378;
static UWORD                  System_SetupHeight = 72;
static UWORD                  Taxman_SetupLeft;
static UWORD                  Taxman_SetupTop;
static UWORD                  Taxman_SetupWidth = 284;
static UWORD                  Taxman_SetupHeight = 56;
static UWORD                  Gang_EditorLeft;
static UWORD                  Gang_EditorTop;
static UWORD                  Gang_EditorWidth = 315;
static UWORD                  Gang_EditorHeight = 106;
static UWORD                  New_User_SetupLeft;
static UWORD                  New_User_SetupTop;
static UWORD                  New_User_SetupWidth = 408;
static UWORD                  New_User_SetupHeight = 160;
static UWORD                  Player_EditorLeft;
static UWORD                  Player_EditorTop;
static UWORD                  Player_EditorWidth = 580;
static UWORD                  Player_EditorHeight = 184;
static UWORD                  User_EditorLeft;
static UWORD                  User_EditorTop;
static UWORD                  User_EditorWidth = 636;
static UWORD                  User_EditorHeight = 176;
static UBYTE                 *System_SetupWdt = (UBYTE *)"System Setup";
static UBYTE                 *Taxman_SetupWdt = (UBYTE *)"Taxman Setup";
static UBYTE                 *Gang_EditorWdt = (UBYTE *)"Gang Editor";
static UBYTE                 *New_User_SetupWdt = (UBYTE *)"New User Setup";
static UBYTE                 *Player_EditorWdt = (UBYTE *)"Player Editor";
static UBYTE                 *User_EditorWdt = (UBYTE *)"User Editor";
static struct TextAttr       *Font, Attr;
static UWORD                  FontX, FontY;
static UWORD                  OffX, OffY;

static UWORD code,menu,menuitem;

struct IntuiText r1fill = {
	0,0,JAM1,1,1,NULL,"Profile",NULL
};
struct MenuItem reports_1 = {
	NULL,					/*	NextItem			*/
	0,0,					/*	LeftEdge, TopEdge	*/
	128,10,					/*	Width, Height		*/
	ITEMTEXT |				/*	Flags				*/
	ITEMENABLED |
	COMMSEQ |
	HIGHCOMP,
	0,						/*	MutualExclude		*/
	(APTR)&r1fill,			/*	ItemFill			*/
	NULL,					/*	SelectFill			*/
	'1',					/*	Command				*/
	NULL,					/*	SubItem				*/
	0						/*	NextSelect			*/
};
struct Menu reports = {
	NULL,					/*	NextMenu			*/
	80,0,					/*	LeftEdge, TopEdge	*/
	80,10,					/*	Width, Height		*/
	MENUENABLED,			/*	Flags				*/
	" Reports ",			/*	MenuName			*/
	&reports_1				/*	MenuItem			*/
};
struct IntuiText function_shutdown = {
	0,0,JAM1,1,1,NULL,"Quit",NULL
};
struct MenuItem shutdown = {
	NULL,					/*	NextItem			*/
	0,72,					/*	LeftEdge, TopEdge	*/
	160,10,					/*	Width, Height		*/
	ITEMTEXT |				/*	Flags				*/
	ITEMENABLED |
	COMMSEQ |
	HIGHCOMP,
	0,						/*	MutualExclude		*/
	(APTR)&function_shutdown,/*	ItemFill			*/
	NULL,					/*	SelectFill			*/
	'Q',					/*	Command				*/
	NULL,					/*	SubItem				*/
	0						/*	NextSelect			*/
};
struct IntuiText function_user = {
	0,0,JAM1,1,1,NULL,"User Editor",NULL
};
struct MenuItem user_editor = {
	&shutdown,				/*	NextItem			*/
	0,60,					/*	LeftEdge, TopEdge	*/
	160,10,					/*	Width, Height		*/
	ITEMTEXT |				/*	Flags				*/
	ITEMENABLED |
	COMMSEQ |
	HIGHCOMP,
	0,						/*	MutualExclude		*/
	(APTR)&function_user,	/*	ItemFill			*/
	NULL,					/*	SelectFill			*/
	'U',					/*	Command				*/
	NULL,					/*	SubItem				*/
	0						/*	NextSelect			*/
};
struct IntuiText function_player = {
	0,0,JAM1,1,1,NULL,"Player Editor",NULL
};
struct MenuItem player_editor = {
	&user_editor,			/*	NextItem			*/
	0,48,					/*	LeftEdge, TopEdge	*/
	160,10,					/*	Width, Height		*/
	ITEMTEXT |				/*	Flags				*/
	ITEMENABLED |
	COMMSEQ |
	HIGHCOMP,
	0,						/*	MutualExclude		*/
	(APTR)&function_player,	/*	ItemFill			*/
	NULL,					/*	SelectFill			*/
	'P',					/*	Command				*/
	NULL,					/*	SubItem				*/
	0						/*	NextSelect			*/
};
struct IntuiText function_new = {
	0,0,JAM1,1,1,NULL,"New User Setup",NULL
};
struct MenuItem new_user = {
	&player_editor,			/*	NextItem			*/
	0,36,					/*	LeftEdge, TopEdge	*/
	160,10,					/*	Width, Height		*/
	ITEMTEXT |				/*	Flags				*/
	ITEMENABLED |
	COMMSEQ |
	HIGHCOMP,
	0,						/*	MutualExclude		*/
	(APTR)&function_new,		/*	ItemFill			*/
	NULL,					/*	SelectFill			*/
	'N',					/*	Command				*/
	NULL,					/*	SubItem				*/
	0						/*	NextSelect			*/
};
struct IntuiText function_gang = {
	0,0,JAM1,1,1,NULL,"Gang Editor",NULL
};
struct MenuItem gang_editor = {
	&new_user,				/*	NextItem			*/
	0,24,					/*	LeftEdge, TopEdge	*/
	160,10,					/*	Width, Height		*/
	ITEMTEXT |				/*	Flags				*/
	ITEMENABLED |
	COMMSEQ |
	HIGHCOMP,
	0,						/*	MutualExclude		*/
	(APTR)&function_gang,		/*	ItemFill			*/
	NULL,					/*	SelectFill			*/
	'G',					/*	Command				*/
	NULL,					/*	SubItem				*/
	0						/*	NextSelect			*/
};
struct IntuiText function_taxman = {
	0,0,JAM1,1,1,NULL,"Taxman Setup",NULL
};
struct MenuItem taxman_setup = {
	&gang_editor,			/*	NextItem			*/
	0,12,					/*	LeftEdge, TopEdge	*/
	160,10,					/*	Width, Height		*/
	ITEMTEXT |				/*	Flags				*/
	ITEMENABLED |
	COMMSEQ |
	HIGHCOMP,
	0,						/*	MutualExclude		*/
	(APTR)&function_taxman,	/*	ItemFill			*/
	NULL,					/*	SelectFill			*/
	'T',					/*	Command				*/
	NULL,					/*	SubItem				*/
	0						/*	NextSelect			*/
};
struct IntuiText function_system = {
	0,0,JAM1,1,1,NULL,"System Setup",NULL
};
struct MenuItem system_setup = {
	&taxman_setup,			/*	NextItem			*/
	0,0,					/*	LeftEdge, TopEdge	*/
	160,10,					/*	Width, Height		*/
	ITEMTEXT |				/*	Flags				*/
	ITEMENABLED |
	COMMSEQ |
	HIGHCOMP,
	0,						/*	MutualExclude		*/
	(APTR)&function_system,	/*	ItemFill			*/
	NULL,					/*	SelectFill			*/
	'S',					/*	Command				*/
	NULL,					/*	SubItem				*/
	0						/*	NextSelect			*/
};
struct Menu function = {
	&reports,				/*	NextMenu			*/
	0,0,					/*	LeftEdge, TopEdge	*/
	80,10,					/*	Width, Height		*/
	MENUENABLED,			/*	Flags				*/
	" Function ",			/*	MenuName			*/
	&system_setup			/*	MenuItem			*/
};

static UWORD System_SetupGTypes[] = {
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	NUMBER_KIND
};

static UWORD Taxman_SetupGTypes[] = {
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND
};

static UWORD Gang_EditorGTypes[] = {
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	BUTTON_KIND,
	TEXT_KIND,
	TEXT_KIND,
	TEXT_KIND,
	TEXT_KIND,
	BUTTON_KIND,
	BUTTON_KIND
};

static UWORD New_User_SetupGTypes[] = {
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND
};

static UWORD Player_EditorGTypes[] = {
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	TEXT_KIND,
	TEXT_KIND,
	TEXT_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	CHECKBOX_KIND
};

static UWORD User_EditorGTypes[] = {
	TEXT_KIND,
	TEXT_KIND,
	BUTTON_KIND,
	NUMBER_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND
};

static struct NewGadget System_SetupNGad[] = {
	124, 5, 185, 13, (UBYTE *)"Sysop's Handle", NULL, GD_SYShandle, PLACETEXT_LEFT, NULL, (APTR)SYShandleClicked,
	124, 22, 253, 13, (UBYTE *)"BBS Name", NULL, GD_SYSname, PLACETEXT_LEFT, NULL, (APTR)SYSnameClicked,
	124, 39, 101, 13, (UBYTE *)"Established", NULL, GD_SYSdate, PLACETEXT_LEFT, NULL, (APTR)SYSdateClicked,
	124, 56, 93, 13, (UBYTE *)"Calls", NULL, GD_SYScalls, PLACETEXT_LEFT, NULL, (APTR)SYScallsClicked,
	293, 56, 37, 13, (UBYTE *)"Best day", NULL, GD_SYSbest, PLACETEXT_LEFT, NULL, NULL
};

static struct NewGadget Taxman_SetupNGad[] = {
	92, 5, 189, 13, (UBYTE *)"Name", NULL, GD_IRSname, PLACETEXT_LEFT, NULL, (APTR)IRSnameClicked,
	92, 22, 173, 13, (UBYTE *)"Money", NULL, GD_IRSmoney, PLACETEXT_LEFT, NULL, (APTR)IRSmoneyClicked,
	92, 39, 53, 13, (UBYTE *)"Post Ratio", NULL, GD_IRSratio, PLACETEXT_LEFT, NULL, (APTR)IRSratioClicked
};

static struct NewGadget Gang_EditorNGad[] = {
	74, 1, 173, 13, (UBYTE *)"Name", NULL, GD_GANGname, PLACETEXT_LEFT, NULL, (APTR)GANGnameClicked,
	74, 18, 45, 13, (UBYTE *)"Leader", NULL, GD_GANGleader, PLACETEXT_LEFT, NULL, (APTR)GANGleaderClicked,
	74, 35, 45, 13, (UBYTE *)"Member#2", NULL, GD_GANGmember2, PLACETEXT_LEFT, NULL, (APTR)GANGmember2Clicked,
	74, 52, 45, 13, (UBYTE *)"Member#3", NULL, GD_GANGmember3, PLACETEXT_LEFT, NULL, (APTR)GANGmember3Clicked,
	74, 69, 45, 13, (UBYTE *)"Member#4", NULL, GD_GANGmember4, PLACETEXT_LEFT, NULL, (APTR)GANGmember4Clicked,
	250, 87, 65, 17, (UBYTE *)"Delete", NULL, GD_GANGdelete, PLACETEXT_IN, NULL, (APTR)GANGdeleteClicked,
	123, 18, 185, 13, NULL, NULL, GD_GANGhandle1, 0, NULL, NULL,
	123, 35, 185, 13, NULL, NULL, GD_GANGhandle2, 0, NULL, NULL,
	123, 52, 185, 13, NULL, NULL, GD_GANGhandle3, 0, NULL, NULL,
	123, 69, 185, 13, NULL, NULL, GD_GANGhandle4, 0, NULL, NULL,
	0, 87, 65, 17, (UBYTE *)"Next", NULL, GD_GANGnext, PLACETEXT_IN, NULL, (APTR)GANGnextClicked,
	125, 87, 65, 17, (UBYTE *)"Prev", NULL, GD_GANGprev, PLACETEXT_IN, NULL, (APTR)GANGprevClicked
};

static struct NewGadget New_User_SetupNGad[] = {
	124, 5, 149, 13, (UBYTE *)"Money in Hand", NULL, GD_NUgold, PLACETEXT_LEFT, NULL, (APTR)NUgoldClicked,
	124, 22, 149, 13, (UBYTE *)"Money in Bank", NULL, GD_NUbank, PLACETEXT_LEFT, NULL, (APTR)NUbankClicked,
	124, 39, 281, 13, (UBYTE *)"Weapon in Hand", NULL, GD_NUweapon, PLACETEXT_LEFT, NULL, (APTR)NUweaponClicked,
	124, 56, 281, 13, (UBYTE *)"Armor on Body", NULL, GD_NUarmor, PLACETEXT_LEFT, NULL, (APTR)NUarmorClicked,
	124, 73, 53, 13, (UBYTE *)"Post Credits", NULL, GD_NUpost, PLACETEXT_LEFT, NULL, (APTR)NUpostClicked,
	124, 90, 53, 13, (UBYTE *)"Upload Credits", NULL, GD_NUupload, PLACETEXT_LEFT, NULL, (APTR)NUuploadClicked,
	124, 107, 93, 13, (UBYTE *)"Byte Credits", NULL, GD_NUbyte, PLACETEXT_LEFT, NULL, (APTR)NUbyteClicked,
	124, 124, 37, 13, (UBYTE *)"File Ratio", NULL, GD_NUfileratio, PLACETEXT_LEFT, NULL, (APTR)NUfileratioClicked,
	124, 141, 37, 13, (UBYTE *)"Byte Ratio", NULL, GD_NUbyteratio, PLACETEXT_LEFT, NULL, (APTR)NUbyteratioClicked
};

static struct NewGadget Player_EditorNGad[] = {
	74, 165, 65, 17, (UBYTE *)"Next", NULL, GD_PLAYERnext, PLACETEXT_IN, NULL, (APTR)PLAYERnextClicked,
	180, 165, 65, 17, (UBYTE *)"Prev", NULL, GD_PLAYERprev, PLACETEXT_IN, NULL, (APTR)PLAYERprevClicked,
	286, 165, 65, 17, (UBYTE *)"Delete", NULL, GD_PLAYERdelete, PLACETEXT_IN, NULL, (APTR)PLAYERdeleteClicked,
	123, 3, 185, 13, NULL, NULL, GD_PLAYERhandle, 0, NULL, NULL,
	108, 107, 161, 13, NULL, NULL, GD_PLAYERrealestatetext, 0, NULL, NULL,
	395, 107, 161, 13, NULL, NULL, GD_PLAYERsecuritytext, 0, NULL, NULL,
	74, 139, 26, 11, (UBYTE *)"Magic", NULL, GD_PLAYERstrsp, PLACETEXT_LEFT, NULL, (APTR)PLAYERstrspClicked,
	104, 139, 26, 11, NULL, NULL, GD_PLAYERintsp, 0, NULL, (APTR)PLAYERintspClicked,
	134, 139, 26, 11, NULL, NULL, GD_PLAYERdexsp, 0, NULL, (APTR)PLAYERdexspClicked,
	164, 139, 26, 11, NULL, NULL, GD_PLAYERchasp, 0, NULL, (APTR)PLAYERchaspClicked,
	194, 139, 26, 11, NULL, NULL, GD_PLAYERshieldsp, 0, NULL, (APTR)PLAYERshieldspClicked,
	224, 139, 26, 11, NULL, NULL, GD_PLAYERhonesp, 0, NULL, (APTR)PLAYERhonespClicked,
	254, 139, 26, 11, NULL, NULL, GD_PLAYERhealsp, 0, NULL, (APTR)PLAYERhealspClicked,
	284, 139, 26, 11, NULL, NULL, GD_PLAYERteleportsp, 0, NULL, (APTR)PLAYERteleportspClicked,
	314, 139, 26, 11, NULL, NULL, GD_PLAYERblastsp, 0, NULL, (APTR)PLAYERblastspClicked,
	344, 139, 26, 11, NULL, NULL, GD_PLAYERressp, 0, NULL, (APTR)PLAYERresspClicked,
	374, 139, 26, 11, NULL, NULL, GD_PLAYERconsp, 0, NULL, (APTR)PLAYERconspClicked,
	404, 139, 26, 11, NULL, NULL, GD_PLAYERtrasp, 0, NULL, (APTR)PLAYERtraspClicked,
	434, 139, 26, 11, NULL, NULL, GD_PLAYERcuresp, 0, NULL, (APTR)PLAYERcurespClicked,
	464, 139, 26, 11, NULL, NULL, GD_PLAYERillsp, 0, NULL, (APTR)PLAYERillspClicked,
	494, 139, 26, 11, NULL, NULL, GD_PLAYERmorphsp, 0, NULL, (APTR)PLAYERmorphspClicked,
	524, 139, 26, 11, NULL, NULL, GD_PLAYERdissp, 0, NULL, (APTR)PLAYERdisspClicked,
	74, 152, 26, 11, (UBYTE *)"Poison", NULL, GD_PLAYERp1, PLACETEXT_LEFT, NULL, (APTR)PLAYERp1Clicked,
	104, 152, 26, 11, NULL, NULL, GD_PLAYERp2, 0, NULL, (APTR)PLAYERp2Clicked,
	134, 152, 26, 11, NULL, NULL, GD_PLAYERp3, 0, NULL, (APTR)PLAYERp3Clicked,
	164, 152, 26, 11, NULL, NULL, GD_PLAYERp4, 0, NULL, (APTR)PLAYERp4Clicked,
	194, 152, 26, 11, NULL, NULL, GD_PLAYERp5, 0, NULL, (APTR)PLAYERp5Clicked,
	224, 152, 26, 11, NULL, NULL, GD_PLAYERp6, 0, NULL, (APTR)PLAYERp6Clicked,
	254, 152, 26, 11, NULL, NULL, GD_PLAYERp7, 0, NULL, (APTR)PLAYERp7Clicked,
	284, 152, 26, 11, NULL, NULL, GD_PLAYERp8, 0, NULL, (APTR)PLAYERp8Clicked,
	314, 152, 26, 11, NULL, NULL, GD_PLAYERp9, 0, NULL, (APTR)PLAYERp9Clicked,
	344, 152, 26, 11, NULL, NULL, GD_PLAYERp10, 0, NULL, (APTR)PLAYERp10Clicked,
	374, 152, 26, 11, NULL, NULL, GD_PLAYERp11, 0, NULL, (APTR)PLAYERp11Clicked,
	404, 152, 26, 11, NULL, NULL, GD_PLAYERp12, 0, NULL, (APTR)PLAYERp12Clicked,
	434, 152, 26, 11, NULL, NULL, GD_PLAYERp13, 0, NULL, (APTR)PLAYERp13Clicked,
	464, 152, 26, 11, NULL, NULL, GD_PLAYERp14, 0, NULL, (APTR)PLAYERp14Clicked,
	494, 152, 26, 11, NULL, NULL, GD_PLAYERp15, 0, NULL, (APTR)PLAYERp15Clicked,
	524, 152, 26, 11, NULL, NULL, GD_PLAYERp16, 0, NULL, (APTR)PLAYERp16Clicked,
	479, 48, 26, 11, (UBYTE *)"Novice", NULL, GD_PLAYERnovice, PLACETEXT_LEFT, NULL, (APTR)PLAYERnoviceClicked,
	74, 3, 45, 13, (UBYTE *)"ID", NULL, GD_PLAYERid, PLACETEXT_LEFT, NULL, (APTR)PLAYERidClicked,
	395, 3, 173, 13, (UBYTE *)"Gang", NULL, GD_PLAYERgang, PLACETEXT_LEFT, NULL, (APTR)PLAYERgangClicked,
	74, 18, 37, 13, (UBYTE *)"Level", NULL, GD_PLAYERlevel, PLACETEXT_LEFT, NULL, (APTR)PLAYERlevelClicked,
	167, 18, 161, 13, (UBYTE *)"Class", NULL, GD_PLAYERclass, PLACETEXT_LEFT, NULL, (APTR)PLAYERclassClicked,
	395, 17, 29, 13, (UBYTE *)"Gender", NULL, GD_PLAYERgender, PLACETEXT_LEFT, NULL, (APTR)PLAYERgenderClicked,
	74, 33, 45, 13, (UBYTE *)"HP", NULL, GD_PLAYERhp, PLACETEXT_LEFT, NULL, (APTR)PLAYERhpClicked,
	167, 33, 45, 13, (UBYTE *)"SP", NULL, GD_PLAYERsp, PLACETEXT_LEFT, NULL, (APTR)PLAYERspClicked,
	272, 32, 37, 13, (UBYTE *)"STR", NULL, GD_PLAYERstr, PLACETEXT_LEFT, NULL, (APTR)PLAYERstrClicked,
	354, 32, 37, 13, (UBYTE *)"INT", NULL, GD_PLAYERint, PLACETEXT_LEFT, NULL, (APTR)PLAYERintClicked,
	439, 32, 37, 13, (UBYTE *)"DEX", NULL, GD_PLAYERdex, PLACETEXT_LEFT, NULL, (APTR)PLAYERdexClicked,
	524, 32, 37, 13, (UBYTE *)"CHA", NULL, GD_PLAYERcha, PLACETEXT_LEFT, NULL, (APTR)PLAYERchaClicked,
	74, 48, 45, 13, (UBYTE *)"Status", NULL, GD_PLAYERstatus, PLACETEXT_LEFT, NULL, (APTR)PLAYERstatusClicked,
	215, 48, 45, 13, (UBYTE *)"Blessed", NULL, GD_PLAYERblessed, PLACETEXT_LEFT, NULL, (APTR)PLAYERblessedClicked,
	346, 48, 45, 13, (UBYTE *)"Cursed", NULL, GD_PLAYERcursed, PLACETEXT_LEFT, NULL, (APTR)PLAYERcursedClicked,
	74, 63, 133, 13, (UBYTE *)"Gold", NULL, GD_PLAYERgold, PLACETEXT_LEFT, NULL, (APTR)PLAYERgoldClicked,
	258, 63, 133, 13, (UBYTE *)"Bank", NULL, GD_PLAYERbank, PLACETEXT_LEFT, NULL, (APTR)PLAYERbankClicked,
	444, 63, 133, 13, (UBYTE *)"Loan", NULL, GD_PLAYERloan, PLACETEXT_LEFT, NULL, (APTR)PLAYERloanClicked,
	74, 77, 277, 13, (UBYTE *)"Weapon", NULL, GD_PLAYERweapon, PLACETEXT_LEFT, NULL, (APTR)PLAYERweaponClicked,
	354, 77, 37, 13, NULL, NULL, GD_PLAYERwcmod, 0, NULL, (APTR)PLAYERwcmodClicked,
	74, 92, 277, 13, (UBYTE *)"Armor", NULL, GD_PLAYERarmor, PLACETEXT_LEFT, NULL, (APTR)PLAYERarmorClicked,
	354, 92, 37, 13, NULL, NULL, GD_PLAYERacmod, 0, NULL, (APTR)PLAYERacmodClicked,
	74, 107, 29, 13, (UBYTE *)"Lives in", NULL, GD_PLAYERrealestate, PLACETEXT_LEFT, NULL, (APTR)PLAYERrealestateClicked,
	362, 107, 29, 13, (UBYTE *)"Security", NULL, GD_PLAYERsecurity, PLACETEXT_LEFT, NULL, (APTR)PLAYERsecurityClicked,
	74, 123, 45, 13, (UBYTE *)"Warship", NULL, GD_PLAYERhull, PLACETEXT_LEFT, NULL, (APTR)PLAYERhullClicked,
	215, 123, 37, 13, (UBYTE *)"Cannon", NULL, GD_PLAYERcannon, PLACETEXT_LEFT, NULL, (APTR)PLAYERcannonClicked,
	325, 123, 26, 11, (UBYTE *)"Ram", NULL, GD_PLAYERram, PLACETEXT_LEFT, NULL, (APTR)PLAYERramClicked
};

static struct NewGadget User_EditorNGad[] = {
	108, 2, 185, 13, NULL, NULL, GD_USERhandle, 0, NULL, NULL,
	100, 122, 129, 13, NULL, NULL, GD_USERaccessname, 0, NULL, NULL,
	248, 151, 65, 17, (UBYTE *)"Delete", NULL, GD_USERdelete, PLACETEXT_IN, NULL, (APTR)USERdeleteClicked,
	605, 47, 29, 13, (UBYTE *)"of", NULL, GD_USERmaxcalls, PLACETEXT_LEFT, NULL, NULL,
	60, 151, 65, 17, (UBYTE *)"Next", NULL, GD_USERnext, PLACETEXT_IN, NULL, (APTR)USERnextClicked,
	154, 151, 65, 17, (UBYTE *)"Prev", NULL, GD_USERprev, PLACETEXT_IN, NULL, (APTR)USERprevClicked,
	60, 2, 45, 13, (UBYTE *)"ID", NULL, GD_USERid, PLACETEXT_LEFT, NULL, (APTR)USERidClicked,
	60, 17, 253, 13, (UBYTE *)"Name", NULL, GD_USERname, PLACETEXT_LEFT, NULL, (APTR)USERnameClicked,
	60, 32, 253, 13, (UBYTE *)"Street", NULL, GD_USERstreet, PLACETEXT_LEFT, NULL, (APTR)USERstreetClicked,
	60, 47, 173, 13, (UBYTE *)"City", NULL, GD_USERcity, PLACETEXT_LEFT, NULL, (APTR)USERcityClicked,
	60, 62, 85, 13, (UBYTE *)"State", NULL, GD_USERstate, PLACETEXT_LEFT, NULL, (APTR)USERstateClicked,
	188, 62, 93, 13, (UBYTE *)"ZIP", NULL, GD_USERzip, PLACETEXT_LEFT, NULL, (APTR)USERzipClicked,
	60, 77, 133, 13, (UBYTE *)"Voice", NULL, GD_USERvoice, PLACETEXT_LEFT, NULL, (APTR)USERvoiceClicked,
	60, 92, 133, 13, (UBYTE *)"Data", NULL, GD_USERdata, PLACETEXT_LEFT, NULL, (APTR)USERdataClicked,
	60, 107, 85, 13, (UBYTE *)"Logon", NULL, GD_USERpassword, PLACETEXT_LEFT, NULL, (APTR)USERpasswordClicked,
	60, 122, 37, 13, (UBYTE *)"Access", NULL, GD_USERaccess, PLACETEXT_LEFT, NULL, (APTR)USERaccessClicked,
	360, 1, 101, 13, (UBYTE *)"Created", NULL, GD_USERcreated, PLACETEXT_LEFT, NULL, (APTR)USERcreatedClicked,
	533, 1, 101, 13, (UBYTE *)"Expires", NULL, GD_USERexpired, PLACETEXT_LEFT, NULL, (APTR)USERexpiredClicked,
	360, 17, 101, 13, (UBYTE *)"DOB", NULL, GD_USERbirth, PLACETEXT_LEFT, NULL, (APTR)USERbirthClicked,
	533, 17, 101, 13, (UBYTE *)"Last on", NULL, GD_USERlaston, PLACETEXT_LEFT, NULL, (APTR)USERlastonClicked,
	360, 32, 29, 13, (UBYTE *)"Sex", NULL, GD_USERsex, PLACETEXT_LEFT, NULL, (APTR)USERsexClicked,
	541, 32, 93, 13, (UBYTE *)"Total Calls", NULL, GD_USERtotalcalls, PLACETEXT_LEFT, NULL, (APTR)USERtotalcallsClicked,
	360, 47, 53, 12, (UBYTE *)"Posts", NULL, GD_USERposts, PLACETEXT_LEFT, NULL, (APTR)USERpostsClicked,
	541, 47, 29, 13, (UBYTE *)"Calls Today", NULL, GD_USERcallstoday, PLACETEXT_LEFT, NULL, (APTR)USERcallstodayClicked,
	380, 97, 53, 13, (UBYTE *)"Uploads", NULL, GD_USERuploads, PLACETEXT_BELOW, NULL, (APTR)USERuploadsClicked,
	498, 97, 53, 13, (UBYTE *)"Downloads", NULL, GD_USERdownloads, PLACETEXT_BELOW, NULL, (APTR)USERdownloadsClicked,
	594, 97, 37, 13, (UBYTE *)"Ratio", NULL, GD_USERfileratio, PLACETEXT_BELOW, NULL, (APTR)USERfileratioClicked,
	360, 122, 93, 13, (UBYTE *)"Bytes", NULL, GD_USERupbyte, PLACETEXT_LEFT, NULL, (APTR)USERupbyteClicked,
	477, 122, 93, 13, NULL, NULL, GD_USERdownbyte, 0, NULL, (APTR)USERdownbyteClicked,
	594, 122, 37, 13, NULL, NULL, GD_USERbyteratio, 0, NULL, (APTR)USERbyteratioClicked
};

static ULONG System_SetupGTags[] = {
	(GTST_MaxChars), 22, (TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 11, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 10, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTNM_Border), TRUE, (TAG_DONE)
};

static ULONG Taxman_SetupGTags[] = {
	(GTST_MaxChars), 22, (TAG_DONE),
	(GTST_MaxChars), 20, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE)
};

static ULONG Gang_EditorGTags[] = {
	(GTST_MaxChars), 20, (TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(TAG_DONE),
	(TAG_DONE)
};

static ULONG New_User_SetupGTags[] = {
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTST_MaxChars), 33, (TAG_DONE),
	(GTST_MaxChars), 33, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 10, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE)
};

static ULONG Player_EditorGTags[] = {
	(TAG_DONE),
	(TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GTST_MaxChars), 20, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTST_MaxChars), 18, (TAG_DONE),
	(GTST_MaxChars), 1, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTST_MaxChars), 33, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTST_MaxChars), 33, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 2, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 2, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(TAG_DONE)
};

static ULONG User_EditorGTags[] = {
	(GTTX_Border), TRUE, (TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GTNM_Border), TRUE, (TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(GTST_MaxChars), 4, (TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 20, (TAG_DONE),
	(GTST_MaxChars), 9, (TAG_DONE),
	(GTST_MaxChars), 10, (TAG_DONE),
	(GTST_MaxChars), 15, (TAG_DONE),
	(GTST_MaxChars), 15, (TAG_DONE),
	(GTST_MaxChars), 9, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTST_MaxChars), 11, (TAG_DONE),
	(GTST_MaxChars), 11, (TAG_DONE),
	(GTST_MaxChars), 11, (TAG_DONE),
	(GTST_MaxChars), 11, (TAG_DONE),
	(GTST_MaxChars), 1, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 10, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 1, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 10, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 10, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGRIGHT), (TAG_DONE)
};

char *money(double n)
{
	static char fnum[48];
	double r,s;
	int i;

	modf(n,&r);
	if(n<1e+05)
		sprintf(fnum,"%.5gc",r);
	else
	if(n<1e+09) {
		modf(n/1e+05,&r);
		sprintf(fnum,"%.5gs",r);
		modf(n-r*1e+05,&s);
		if(s>0.) {
			i=strlen(fnum);
			sprintf(&fnum[i],",%.5gc",s);
		}
	}
	else
	if(n<1e+13) {
		modf(n/1e+09,&r);
		sprintf(fnum,"%.4gg",r);
		modf((n-r*1e+09)/1e+05,&s);
		if(s>0.) {
			i=strlen(fnum);
			sprintf(&fnum[i],",%.5gs",s);
		}
	}
	else {
		modf(n/1e+13,&r);
		sprintf(fnum,"%.8gp",r);
		modf((n-r*1e+13)/1e+09,&s);
		if(s>0.) {
			i=strlen(fnum);
			sprintf(&fnum[i],",%.5gg",s);
		}
	}
	return(fnum);
}

int RPGserver(char command,UBYTE *p)
{
	static UBYTE flag;

	strcpy(server.client,"_SYS");
	server.command=command;
	server.parameter=p;
	server.result=&flag;
	PutMsg(RPGport,(struct Message *)&server);
	WaitPort(RPGreply);
	if((response=(struct RPGserver *)GetMsg(RPGreply))) {
		switch(command) {
			case SERVER_CONNECT:
				ServerTable=(struct ServerTable *)server.parameter;
				break;
			case SERVER_LOCK:
				if(!flag)
					DisplayBeep(NULL);
				break;
		}
	}
	return(flag);
}

int NewUserSetupClicked( void )
{
	if(!OpenNew_User_SetupWindow()) {
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUgold],New_User_SetupWnd,NULL,
			(GTST_String),(ULONG)money(NEW->Gold),
			(TAG_DONE));
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUbank],New_User_SetupWnd,NULL,
			(GTST_String),(ULONG)money(NEW->Bank),
			(TAG_DONE));
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUweapon],New_User_SetupWnd,NULL,
			(GTST_String),(ULONG)NEW->Weapon,
			(TAG_DONE));
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUarmor],New_User_SetupWnd,NULL,
			(GTST_String),(ULONG)NEW->Armor,
			(TAG_DONE));
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUpost],New_User_SetupWnd,NULL,
			(GTIN_Number),(ULONG)NEW->Posts,
			(TAG_DONE));
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUupload],New_User_SetupWnd,NULL,
			(GTIN_Number),(ULONG)NEW->Uploads,
			(TAG_DONE));
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUbyte],New_User_SetupWnd,NULL,
			(GTIN_Number),(ULONG)NEW->UpByte,
			(TAG_DONE));
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUfileratio],New_User_SetupWnd,NULL,
			(GTIN_Number),(ULONG)NEW->FileRatio,
			(TAG_DONE));
		GT_SetGadgetAttrs(New_User_SetupGadgets[GD_NUbyteratio],New_User_SetupWnd,NULL,
			(GTIN_Number),(ULONG)NEW->ByteRatio,
			(TAG_DONE));
		FOREVER {
			Wait(1L<<New_User_SetupWnd->UserPort->mp_SigBit);
			if(HandleNew_User_SetupIDCMP()=='Q')
				break;
		}
		gold(&NEW->Gold,GetString(New_User_SetupGadgets[GD_NUgold]));
		gold(&NEW->Bank,GetString(New_User_SetupGadgets[GD_NUbank]));
		strncpy(NEW->Weapon,GetString(New_User_SetupGadgets[GD_NUweapon]),sizeof(NEW->Weapon));
		strncpy(NEW->Armor,GetString(New_User_SetupGadgets[GD_NUarmor]),sizeof(NEW->Armor));
		NEW->Posts=GetNumber(New_User_SetupGadgets[GD_NUpost]);
		NEW->Uploads=GetNumber(New_User_SetupGadgets[GD_NUupload]);
		NEW->UpByte=GetNumber(New_User_SetupGadgets[GD_NUbyte]);
		NEW->FileRatio=GetNumber(New_User_SetupGadgets[GD_NUfileratio]);
		NEW->ByteRatio=GetNumber(New_User_SetupGadgets[GD_NUbyteratio]);
		NEW->Novice='Y';
		RPGserver(SERVER_PUTUSER,(UBYTE *)NEW);
		CloseNew_User_SetupWindow();
	}
	return(TRUE);
}

int TaxmanSetupClicked( void )
{
	if(!OpenTaxman_SetupWindow()) {
		GT_SetGadgetAttrs(Taxman_SetupGadgets[GD_IRSname],Taxman_SetupWnd,NULL,
			(GTST_String),(ULONG)IRS->Handle,
			(TAG_DONE));
		GT_SetGadgetAttrs(Taxman_SetupGadgets[GD_IRSmoney],Taxman_SetupWnd,NULL,
			(GTST_String),(ULONG)money(IRS->Bank),
			(TAG_DONE));
		GT_SetGadgetAttrs(Taxman_SetupGadgets[GD_IRSratio],Taxman_SetupWnd,NULL,
			(GTIN_Number),(ULONG)IRS->Posts,
			(TAG_DONE));
		FOREVER {
			Wait(1L<<Taxman_SetupWnd->UserPort->mp_SigBit);
			if(HandleTaxman_SetupIDCMP()=='Q')
				break;
		}
		strncpy(IRS->Handle,GetString(Taxman_SetupGadgets[GD_IRSname]),sizeof(IRS->Handle));
		gold(&IRS->Bank,GetString(Taxman_SetupGadgets[GD_IRSmoney]));
		IRS->Posts=GetNumber(Taxman_SetupGadgets[GD_IRSratio]);
		RPGserver(SERVER_PUTUSER,(UBYTE *)IRS);
		CloseTaxman_SetupWindow();
	}
	return(TRUE);
}

int SystemSetupClicked( void )
{
	if(!OpenSystem_SetupWindow()) {
		GT_SetGadgetAttrs(System_SetupGadgets[GD_SYShandle],System_SetupWnd,NULL,
			(GTST_String),(ULONG)SYS->Handle,
			(TAG_DONE));
		GT_SetGadgetAttrs(System_SetupGadgets[GD_SYSname],System_SetupWnd,NULL,
			(GTST_String),(ULONG)SYS->Name,
			(TAG_DONE));
		fdate(dated,SYS->CreateDate);
		GT_SetGadgetAttrs(System_SetupGadgets[GD_SYSdate],System_SetupWnd,NULL,
			(GTST_String),(ULONG)&dated[4],
			(TAG_DONE));
		GT_SetGadgetAttrs(System_SetupGadgets[GD_SYScalls],System_SetupWnd,NULL,
			(GTIN_Number),(ULONG)SYS->History.Calls,
			(TAG_DONE));
		GT_SetGadgetAttrs(System_SetupGadgets[GD_SYSbest],System_SetupWnd,NULL,
			(GTNM_Number),(ULONG)SYS->Current.Calls,
			(TAG_DONE));
		FOREVER {
			Wait(1L<<System_SetupWnd->UserPort->mp_SigBit);
			if(HandleSystem_SetupIDCMP()=='Q')
				break;
		}
		strncpy(SYS->Handle,GetString(System_SetupGadgets[GD_SYShandle]),sizeof(SYS->Handle));
		strncpy(SYS->Name,GetString(System_SetupGadgets[GD_SYSname]),sizeof(SYS->Name));
		SYS->History.Calls=GetNumber(System_SetupGadgets[GD_SYScalls]);
		RPGserver(SERVER_PUTUSER,(UBYTE *)SYS);
		CloseSystem_SetupWindow();
	}
	return(TRUE);
}

void DisplayGANG(void)
{
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGname],Gang_EditorWnd,NULL,
		(GTST_String),(ULONG)GANG.Name,
		(TAG_DONE));
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGleader],Gang_EditorWnd,NULL,
		(GTST_String),(ULONG)GANG.MemberID[0],
		(TAG_DONE));
	strncpy(USER.ID,GANG.MemberID[0],sizeof(USER.ID));
	RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGhandle1],Gang_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGmember2],Gang_EditorWnd,NULL,
		(GTST_String),(ULONG)GANG.MemberID[1],
		(TAG_DONE));
	strncpy(USER.ID,GANG.MemberID[1],sizeof(USER.ID));
	RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGhandle2],Gang_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGmember3],Gang_EditorWnd,NULL,
		(GTST_String),(ULONG)GANG.MemberID[2],
		(TAG_DONE));
	strncpy(USER.ID,GANG.MemberID[2],sizeof(USER.ID));
	RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGhandle3],Gang_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGmember4],Gang_EditorWnd,NULL,
		(GTST_String),(ULONG)GANG.MemberID[3],
		(TAG_DONE));
	strncpy(USER.ID,GANG.MemberID[3],sizeof(USER.ID));
	RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGhandle4],Gang_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGdelete],Gang_EditorWnd,NULL,
		(GA_Disabled), strlen(GANG.Name) ? FALSE : TRUE,
		(TAG_DONE));
}

void UpdateGANG(void)
{
	if(strlen(GANG.Name)) {
		strncpy(GANG.MemberID[0],GetString(Gang_EditorGadgets[GD_GANGleader]),sizeof(GANG.MemberID[0]));
		strncpy(GANG.MemberID[1],GetString(Gang_EditorGadgets[GD_GANGmember2]),sizeof(GANG.MemberID[1]));
		strncpy(GANG.MemberID[2],GetString(Gang_EditorGadgets[GD_GANGmember3]),sizeof(GANG.MemberID[2]));
		strncpy(GANG.MemberID[3],GetString(Gang_EditorGadgets[GD_GANGmember4]),sizeof(GANG.MemberID[3]));
		RPGserver(SERVER_PUTGANG,(UBYTE *)&GANG);
	}
}

int GangEditorClicked( void )
{
	if(!OpenGang_EditorWindow()) {
		memset(&GANG,0,sizeof(GANG));
		FOREVER {
			Wait(1L<<Gang_EditorWnd->UserPort->mp_SigBit);
			if(HandleGang_EditorIDCMP()=='Q')
				break;
		}
		UpdateGANG();
		CloseGang_EditorWindow();
	}
	return(TRUE);
}

void DisplayPLAYER(void)
{
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERid],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.ID,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERhandle],Player_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	sprintf(GANG.Name,"%.20s",USER.Gang);
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERgang],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)GANG.Name,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERlevel],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.Level,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERclass],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Class,
		(TAG_DONE));
	sprintf(dated,"%c",USER.Gender);
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERgender],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)dated,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERhp],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.HP,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERsp],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.SP,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERstr],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.STR,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERint],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.INT,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERdex],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.DEX,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERcha],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.CHA,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERstatus],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Status,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERblessed],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Blessed, (GA_Disabled), strlen(USER.Cursed) ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERcursed],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Cursed, (GA_Disabled), strlen(USER.Blessed) ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERnovice],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Novice=='Y' ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERgold],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)money(USER.Gold),
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERbank],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)money(USER.Bank),
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERloan],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)money(USER.Loan),
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERweapon],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Weapon,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERwcmod],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.WCmod,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERarmor],Player_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Armor,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERacmod],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.ACmod,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERrealestate],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.RealEstate,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERrealestatetext],Player_EditorWnd,NULL,
		(GTTX_Text),(ULONG)ServerTable->realestate[USER.RealEstate]->Name,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERsecurity],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.Security,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERsecuritytext],Player_EditorWnd,NULL,
		(GTTX_Text),(ULONG)ServerTable->security[USER.Security]->Name,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERhull],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.Hull,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERcannon],Player_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.Cannon, (GA_Disabled), USER.Hull ? FALSE : TRUE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERram],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Ram=='Y' ? TRUE : FALSE, (GA_Disabled), USER.Hull ? FALSE : TRUE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERstrsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & STRENGTH_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERintsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & INTELLECT_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERdexsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & DEXTERITY_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERchasp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & CHARISMA_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERshieldsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & SHIELD_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERhonesp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & HONE_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERhealsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & HEAL_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERteleportsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & TELEPORT_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERblastsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & BLAST_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERressp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & RESURRECT_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERconsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & CONFUSION_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERtrasp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & TRANSMUTE_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERcuresp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & CURE_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERillsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & ILLUSION_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERdissp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & DISINTEGRATE_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERmorphsp],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Spell & MORPH_SPELL ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp1],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<0 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp2],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<1 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp3],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<2 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp4],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<3 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp5],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<4 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp6],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<5 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp7],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<6 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp8],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<7 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp9],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<8 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp10],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<9 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp11],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<10 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp12],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<11 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp13],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<12 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp14],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<13 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp15],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<14 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERp16],Player_EditorWnd,NULL,
		(GTCB_Checked),USER.Poison & 1L<<15 ? TRUE : FALSE,
		(TAG_DONE));
	GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERdelete],Player_EditorWnd,NULL,
		(GA_Disabled), strlen(USER.ID) ? FALSE : TRUE,
		(TAG_DONE));
}

void UpdatePLAYER(void)
{
	if(strlen(USER.ID)) {
		strncpy(USER.Gang,GetString(Player_EditorGadgets[GD_PLAYERgang]),20);
		USER.Level=GetNumber(Player_EditorGadgets[GD_PLAYERlevel]);
		strncpy(USER.Class,GetString(Player_EditorGadgets[GD_PLAYERclass]),sizeof(USER.Class));
		strncpy(&USER.Gender,GetString(Player_EditorGadgets[GD_PLAYERgender]),1);
		USER.HP=GetNumber(Player_EditorGadgets[GD_PLAYERhp]);
		USER.SP=GetNumber(Player_EditorGadgets[GD_PLAYERsp]);
		USER.STR=GetNumber(Player_EditorGadgets[GD_PLAYERstr]);
		USER.INT=GetNumber(Player_EditorGadgets[GD_PLAYERint]);
		USER.DEX=GetNumber(Player_EditorGadgets[GD_PLAYERdex]);
		USER.CHA=GetNumber(Player_EditorGadgets[GD_PLAYERcha]);
		strncpy(USER.Status,GetString(Player_EditorGadgets[GD_PLAYERstatus]),sizeof(USER.Status));
		strncpy(USER.Blessed,GetString(Player_EditorGadgets[GD_PLAYERblessed]),sizeof(USER.Blessed));
		strncpy(USER.Cursed,GetString(Player_EditorGadgets[GD_PLAYERcursed]),sizeof(USER.Cursed));
		USER.Novice=(Player_EditorGadgets[GD_PLAYERnovice]->Flags & GFLG_SELECTED) ? 'Y' : 'N';
		gold(&USER.Gold,GetString(Player_EditorGadgets[GD_PLAYERgold]));
		gold(&USER.Bank,GetString(Player_EditorGadgets[GD_PLAYERbank]));
		gold(&USER.Loan,GetString(Player_EditorGadgets[GD_PLAYERloan]));
		strncpy(USER.Weapon,GetString(Player_EditorGadgets[GD_PLAYERweapon]),sizeof(USER.Weapon));
		USER.WCmod=GetNumber(Player_EditorGadgets[GD_PLAYERwcmod]);
		strncpy(USER.Armor,GetString(Player_EditorGadgets[GD_PLAYERarmor]),sizeof(USER.Armor));
		USER.ACmod=GetNumber(Player_EditorGadgets[GD_PLAYERacmod]);
		USER.RealEstate=GetNumber(Player_EditorGadgets[GD_PLAYERrealestate]);
		USER.Security=GetNumber(Player_EditorGadgets[GD_PLAYERsecurity]);
		USER.Hull=GetNumber(Player_EditorGadgets[GD_PLAYERhull]);
		USER.Cannon=GetNumber(Player_EditorGadgets[GD_PLAYERcannon]);
		USER.Ram=(Player_EditorGadgets[GD_PLAYERram]->Flags & GFLG_SELECTED) ? 'Y' : 'N';
		USER.Spell=0;
		if(Player_EditorGadgets[GD_PLAYERstrsp]->Flags & GFLG_SELECTED)
			USER.Spell|=STRENGTH_SPELL;
		if(Player_EditorGadgets[GD_PLAYERintsp]->Flags & GFLG_SELECTED)
			USER.Spell|=INTELLECT_SPELL;
		if(Player_EditorGadgets[GD_PLAYERdexsp]->Flags & GFLG_SELECTED)
			USER.Spell|=DEXTERITY_SPELL;
		if(Player_EditorGadgets[GD_PLAYERchasp]->Flags & GFLG_SELECTED)
			USER.Spell|=CHARISMA_SPELL;
		if(Player_EditorGadgets[GD_PLAYERshieldsp]->Flags & GFLG_SELECTED)
			USER.Spell|=SHIELD_SPELL;
		if(Player_EditorGadgets[GD_PLAYERhonesp]->Flags & GFLG_SELECTED)
			USER.Spell|=HONE_SPELL;
		if(Player_EditorGadgets[GD_PLAYERhealsp]->Flags & GFLG_SELECTED)
			USER.Spell|=HEAL_SPELL;
		if(Player_EditorGadgets[GD_PLAYERteleportsp]->Flags & GFLG_SELECTED)
			USER.Spell|=TELEPORT_SPELL;
		if(Player_EditorGadgets[GD_PLAYERblastsp]->Flags & GFLG_SELECTED)
			USER.Spell|=BLAST_SPELL;
		if(Player_EditorGadgets[GD_PLAYERressp]->Flags & GFLG_SELECTED)
			USER.Spell|=RESURRECT_SPELL;
		if(Player_EditorGadgets[GD_PLAYERconsp]->Flags & GFLG_SELECTED)
			USER.Spell|=CONFUSION_SPELL;
		if(Player_EditorGadgets[GD_PLAYERtrasp]->Flags & GFLG_SELECTED)
			USER.Spell|=TRANSMUTE_SPELL;
		if(Player_EditorGadgets[GD_PLAYERcuresp]->Flags & GFLG_SELECTED)
			USER.Spell|=CURE_SPELL;
		if(Player_EditorGadgets[GD_PLAYERillsp]->Flags & GFLG_SELECTED)
			USER.Spell|=ILLUSION_SPELL;
		if(Player_EditorGadgets[GD_PLAYERdissp]->Flags & GFLG_SELECTED)
			USER.Spell|=DISINTEGRATE_SPELL;
		if(Player_EditorGadgets[GD_PLAYERmorphsp]->Flags & GFLG_SELECTED)
			USER.Spell|=MORPH_SPELL;
		USER.Poison=0;
		if(Player_EditorGadgets[GD_PLAYERp1]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<0;
		if(Player_EditorGadgets[GD_PLAYERp2]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<1;
		if(Player_EditorGadgets[GD_PLAYERp3]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<2;
		if(Player_EditorGadgets[GD_PLAYERp4]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<3;
		if(Player_EditorGadgets[GD_PLAYERp5]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<4;
		if(Player_EditorGadgets[GD_PLAYERp6]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<5;
		if(Player_EditorGadgets[GD_PLAYERp7]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<6;
		if(Player_EditorGadgets[GD_PLAYERp8]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<7;
		if(Player_EditorGadgets[GD_PLAYERp9]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<8;
		if(Player_EditorGadgets[GD_PLAYERp10]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<9;
		if(Player_EditorGadgets[GD_PLAYERp11]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<10;
		if(Player_EditorGadgets[GD_PLAYERp12]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<11;
		if(Player_EditorGadgets[GD_PLAYERp13]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<12;
		if(Player_EditorGadgets[GD_PLAYERp14]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<13;
		if(Player_EditorGadgets[GD_PLAYERp15]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<14;
		if(Player_EditorGadgets[GD_PLAYERp16]->Flags & GFLG_SELECTED)
			USER.Poison|=1L<<15;
		RPGserver(SERVER_PUTUSER,(UBYTE *)&USER);
	}
}

int PlayerEditorClicked( void )
{
	if(!OpenPlayer_EditorWindow()) {
		memset(&USER,0,sizeof(USER));
		FOREVER {
			Wait(1L<<Player_EditorWnd->UserPort->mp_SigBit);
			if(HandlePlayer_EditorIDCMP()=='Q')
				break;
		}
		UpdatePLAYER();
		ClosePlayer_EditorWindow();
	}
	return(TRUE);
}

void DisplayUSER(void)
{
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERid],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.ID,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERhandle],User_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERname],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Name,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERstreet],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Street,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERcity],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.City,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERstate],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.State,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERzip],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Zip,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERvoice],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.VoicePhone,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERdata],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.DataPhone,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERpassword],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Password,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERaccess],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.Access,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERaccessname],User_EditorWnd,NULL,
		(GTTX_Text),(ULONG)ServerTable->access[USER.Access]->Name,
		(TAG_DONE));
	fdate(dated,USER.CreateDate);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERcreated],User_EditorWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	fdate(dated,USER.ExpireDate);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERexpired],User_EditorWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	fdate(dated,USER.BirthDate);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERbirth],User_EditorWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	fdate(dated,USER.LastDate);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERlaston],User_EditorWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	sprintf(dated,"%c",USER.Sex);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERsex],User_EditorWnd,NULL,
		(GTST_String),(ULONG)dated,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERtotalcalls],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.History.Calls,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERposts],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.Posts,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERcallstoday],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.CallsToday,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERmaxcalls],User_EditorWnd,NULL,
		(GTNM_Number),(ULONG)ServerTable->access[USER.Access]->Calls,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERuploads],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.Uploads,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERdownloads],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.Downloads,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERfileratio],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.FileRatio,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERupbyte],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.UpByte,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERdownbyte],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.DownByte,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERbyteratio],User_EditorWnd,NULL,
		(GTIN_Number),(ULONG)USER.ByteRatio,
		(TAG_DONE));
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERdelete],User_EditorWnd,NULL,
		(GA_Disabled), strlen(USER.ID) ? FALSE : TRUE,
		(TAG_DONE));
}

void UpdateUSER(void)
{
	if(strlen(USER.ID)) {
		strncpy(USER.Name,GetString(User_EditorGadgets[GD_USERname]),sizeof(USER.Name));
		strncpy(USER.Street,GetString(User_EditorGadgets[GD_USERstreet]),sizeof(USER.Street));
		strncpy(USER.City,GetString(User_EditorGadgets[GD_USERcity]),sizeof(USER.City));
		strncpy(USER.State,GetString(User_EditorGadgets[GD_USERstate]),sizeof(USER.State));
		strncpy(USER.Zip,GetString(User_EditorGadgets[GD_USERzip]),sizeof(USER.Zip));
		strncpy(USER.VoicePhone,GetString(User_EditorGadgets[GD_USERvoice]),sizeof(USER.VoicePhone));
		strncpy(USER.DataPhone,GetString(User_EditorGadgets[GD_USERdata]),sizeof(USER.DataPhone));
		strncpy(USER.Password,GetString(User_EditorGadgets[GD_USERpassword]),sizeof(USER.Password));
		USER.Access=GetNumber(User_EditorGadgets[GD_USERaccess]);
		strncpy(&USER.Sex,GetString(User_EditorGadgets[GD_USERsex]),1);
		USER.History.Calls=GetNumber(User_EditorGadgets[GD_USERtotalcalls]);
		USER.Posts=GetNumber(User_EditorGadgets[GD_USERposts]);
		USER.CallsToday=GetNumber(User_EditorGadgets[GD_USERcallstoday]);
		USER.Uploads=GetNumber(User_EditorGadgets[GD_USERuploads]);
		USER.Downloads=GetNumber(User_EditorGadgets[GD_USERdownloads]);
		USER.FileRatio=GetNumber(User_EditorGadgets[GD_USERfileratio]);
		USER.UpByte=GetNumber(User_EditorGadgets[GD_USERupbyte]);
		USER.DownByte=GetNumber(User_EditorGadgets[GD_USERdownbyte]);
		USER.ByteRatio=GetNumber(User_EditorGadgets[GD_USERbyteratio]);
		RPGserver(SERVER_PUTUSER,(UBYTE *)&USER);
	}
}

int UserEditorClicked( void )
{
	if(!OpenUser_EditorWindow()) {
		memset(&USER,0,sizeof(USER));
		FOREVER {
			Wait(1L<<User_EditorWnd->UserPort->mp_SigBit);
			if(HandleUser_EditorIDCMP()=='Q')
				break;
		}
		UpdateUSER();
		CloseUser_EditorWindow();
	}
	return(TRUE);
}

int NUgoldClicked( void )
{
	return(TRUE);
}

int NUbankClicked( void )
{
	return(TRUE);
}

int NUweaponClicked( void )
{
	return(TRUE);
}

int NUarmorClicked( void )
{
	return(TRUE);
}

int NUpostClicked( void )
{
	return(TRUE);
}

int NUuploadClicked( void )
{
	return(TRUE);
}

int NUbyteClicked( void )
{
	return(TRUE);
}

int NUfileratioClicked( void )
{
	return(TRUE);
}

int NUbyteratioClicked( void )
{
	return(TRUE);
}

int IRSnameClicked( void )
{
	return(TRUE);
}

int IRSmoneyClicked( void )
{
	return(TRUE);
}

int IRSratioClicked( void )
{
	return(TRUE);
}

int SYShandleClicked( void )
{
	return(TRUE);
}

int SYSnameClicked( void )
{
	return(TRUE);
}

int SYSdateClicked( void )
{
	julian(&SYS->CreateDate,GetString(System_SetupGadgets[GD_SYSdate]));
	fdate(dated,SYS->CreateDate);
	GT_SetGadgetAttrs(System_SetupGadgets[GD_SYSdate],System_SetupWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	return(TRUE);
}

int SYScallsClicked( void )
{
	return(TRUE);
}

int GANGnameClicked( void )
{
	UpdateGANG();
	strncpy(GANG.Name,GetString(Gang_EditorGadgets[GD_GANGname]),sizeof(GANG.Name));
	RPGserver(SERVER_GETGANG,(UBYTE *)&GANG);
	DisplayGANG();
	return(TRUE);
}

int GANGleaderClicked( void )
{
	strncpy(GANG.MemberID[0],GetString(Gang_EditorGadgets[GD_GANGleader]),sizeof(GANG.MemberID[0]));
	strncpy(USER.ID,GANG.MemberID[0],sizeof(USER.ID));
	RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGhandle1],Gang_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	return(TRUE);
}

int GANGmember2Clicked( void )
{
	strncpy(GANG.MemberID[1],GetString(Gang_EditorGadgets[GD_GANGmember2]),sizeof(GANG.MemberID[1]));
	strncpy(USER.ID,GANG.MemberID[1],sizeof(USER.ID));
	RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGhandle2],Gang_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	return(TRUE);
}

int GANGmember3Clicked( void )
{
	strncpy(GANG.MemberID[2],GetString(Gang_EditorGadgets[GD_GANGmember3]),sizeof(GANG.MemberID[2]));
	strncpy(USER.ID,GANG.MemberID[2],sizeof(USER.ID));
	RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGhandle3],Gang_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	return(TRUE);
}

int GANGmember4Clicked( void )
{
	strncpy(GANG.MemberID[3],GetString(Gang_EditorGadgets[GD_GANGmember4]),sizeof(GANG.MemberID[3]));
	strncpy(USER.ID,GANG.MemberID[3],sizeof(USER.ID));
	RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	GT_SetGadgetAttrs(Gang_EditorGadgets[GD_GANGhandle4],Gang_EditorWnd,NULL,
		(GTTX_Text),(ULONG)USER.Handle,
		(TAG_DONE));
	return(TRUE);
}

int GANGnextClicked( void )
{
	UpdateGANG();
	RPGserver(SERVER_NEXTGANG,(UBYTE *)&GANG);
	DisplayGANG();
	return(TRUE);
}

int GANGprevClicked( void )
{
	UpdateGANG();
	RPGserver(SERVER_PREVGANG,(UBYTE *)&GANG);
	DisplayGANG();
	return(TRUE);
}

int GANGdeleteClicked( void )
{
	int i;

	for(i=0; i<4; i++)
		if(strlen(GANG.MemberID[i])) {
			strncpy(USER.ID,GANG.MemberID[i],sizeof(USER.ID));
			RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
			memset(USER.Gang,0,20);
			RPGserver(SERVER_PUTUSER,(UBYTE *)&USER);
		}
	RPGserver(SERVER_DELGANG,(UBYTE *)&GANG);
	RPGserver(SERVER_NEXTGANG,(UBYTE *)&GANG);
	DisplayGANG();
	return(TRUE);
}

int PLAYERnextClicked( void )
{
	UpdatePLAYER();
	RPGserver(SERVER_NEXTUSER,(UBYTE *)&USER);
	DisplayPLAYER();
	return(TRUE);
}

int PLAYERprevClicked( void )
{
	UpdatePLAYER();
	RPGserver(SERVER_PREVUSER,(UBYTE *)&USER);
	DisplayPLAYER();
	return(TRUE);
}

int PLAYERdeleteClicked( void )
{
	char filename[81],node[41];
	int i;

	for(i=0; i<999; i++) {
		sprintf(node,"%s.%03d",USER.ID,i);
		strmfp(filename,EMAILpath,node);
		if(remove(filename))
			break;
	}
	strmfp(filename,NOTESpath,USER.ID);
	remove(filename);
	if(RPGserver(SERVER_DELUSER,(UBYTE *)&USER))
		memset(&USER,0,sizeof(USER));
	DisplayPLAYER();
	return(TRUE);
}

int PLAYERstrspClicked( void )
{
	return(TRUE);
}

int PLAYERintspClicked( void )
{
	return(TRUE);
}

int PLAYERdexspClicked( void )
{
	return(TRUE);
}

int PLAYERchaspClicked( void )
{
	return(TRUE);
}

int PLAYERshieldspClicked( void )
{
	return(TRUE);
}

int PLAYERhonespClicked( void )
{
	return(TRUE);
}

int PLAYERhealspClicked( void )
{
	return(TRUE);
}

int PLAYERteleportspClicked( void )
{
	return(TRUE);
}

int PLAYERblastspClicked( void )
{
	return(TRUE);
}

int PLAYERresspClicked( void )
{
	return(TRUE);
}

int PLAYERconspClicked( void )
{
	return(TRUE);
}

int PLAYERtraspClicked( void )
{
	return(TRUE);
}

int PLAYERcurespClicked( void )
{
	return(TRUE);
}

int PLAYERillspClicked( void )
{
	return(TRUE);
}

int PLAYERmorphspClicked( void )
{
	return(TRUE);
}

int PLAYERdisspClicked( void )
{
	return(TRUE);
}

int PLAYERp1Clicked( void )
{
	return(TRUE);
}

int PLAYERp2Clicked( void )
{
	return(TRUE);
}

int PLAYERp3Clicked( void )
{
	return(TRUE);
}

int PLAYERp4Clicked( void )
{
	return(TRUE);
}

int PLAYERp5Clicked( void )
{
	return(TRUE);
}

int PLAYERp6Clicked( void )
{
	return(TRUE);
}

int PLAYERp7Clicked( void )
{
	return(TRUE);
}

int PLAYERp8Clicked( void )
{
	return(TRUE);
}

int PLAYERp9Clicked( void )
{
	return(TRUE);
}

int PLAYERp10Clicked( void )
{
	return(TRUE);
}

int PLAYERp11Clicked( void )
{
	return(TRUE);
}

int PLAYERp12Clicked( void )
{
	return(TRUE);
}

int PLAYERp13Clicked( void )
{
	return(TRUE);
}

int PLAYERp14Clicked( void )
{
	return(TRUE);
}

int PLAYERp15Clicked( void )
{
	return(TRUE);
}

int PLAYERp16Clicked( void )
{
	return(TRUE);
}

int PLAYERnoviceClicked( void )
{
	return(TRUE);
}

int PLAYERidClicked( void )
{
	UpdatePLAYER();
	strncpy(USER.ID,GetString(Player_EditorGadgets[GD_PLAYERid]),sizeof(USER.ID));
	if(USER.ID[0]!='_')
		RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	else
		memset(&USER,0,sizeof(USER));
	DisplayPLAYER();
	return(TRUE);
}

int PLAYERgangClicked( void )
{
	return(TRUE);
}

int PLAYERlevelClicked( void )
{
	return(TRUE);
}

int PLAYERclassClicked( void )
{
	return(TRUE);
}

int PLAYERgenderClicked( void )
{
	return(TRUE);
}

int PLAYERhpClicked( void )
{
	return(TRUE);
}

int PLAYERspClicked( void )
{
	return(TRUE);
}

int PLAYERstrClicked( void )
{
	USER.STR=GetNumber(Player_EditorGadgets[GD_PLAYERstr]);
	if(USER.STR>100) {
		USER.STR=100;
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERintClicked( void )
{
	USER.INT=GetNumber(Player_EditorGadgets[GD_PLAYERint]);
	if(USER.INT>100) {
		USER.INT=100;
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERdexClicked( void )
{
	USER.DEX=GetNumber(Player_EditorGadgets[GD_PLAYERdex]);
	if(USER.DEX>100) {
		USER.DEX=100;
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERchaClicked( void )
{
	USER.CHA=GetNumber(Player_EditorGadgets[GD_PLAYERcha]);
	if(USER.CHA>100) {
		USER.CHA=100;
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERstatusClicked( void )
{
	return(TRUE);
}

int PLAYERblessedClicked( void )
{
	if(strcmp(USER.Blessed,GetString(Player_EditorGadgets[GD_PLAYERblessed]))) {
		strncpy(USER.Blessed,GetString(Player_EditorGadgets[GD_PLAYERblessed]),sizeof(USER.Blessed));
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERcursedClicked( void )
{
	if(strcmp(USER.Cursed,GetString(Player_EditorGadgets[GD_PLAYERcursed]))) {
		strncpy(USER.Cursed,GetString(Player_EditorGadgets[GD_PLAYERcursed]),sizeof(USER.Cursed));
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERgoldClicked( void )
{
	return(TRUE);
}

int PLAYERbankClicked( void )
{
	return(TRUE);
}

int PLAYERloanClicked( void )
{
	return(TRUE);
}

int PLAYERweaponClicked( void )
{
	return(TRUE);
}

int PLAYERwcmodClicked( void )
{
	return(TRUE);
}

int PLAYERarmorClicked( void )
{
	return(TRUE);
}

int PLAYERacmodClicked( void )
{
	return(TRUE);
}

int PLAYERrealestateClicked( void )
{
	int i;
	i=GetNumber(Player_EditorGadgets[GD_PLAYERrealestate]);
	if(i>=0 && i<ServerTable->NumRealEstate) {
		GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERrealestatetext],Player_EditorWnd,NULL,
			(GTTX_Text),(ULONG)ServerTable->realestate[i]->Name,
			(TAG_DONE));
	}
	else {
		DisplayBeep(NULL);
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERsecurityClicked( void )
{
	int i;
	i=GetNumber(Player_EditorGadgets[GD_PLAYERsecurity]);
	if(i>=0 && i<ServerTable->NumSecurity) {
		GT_SetGadgetAttrs(Player_EditorGadgets[GD_PLAYERsecuritytext],Player_EditorWnd,NULL,
			(GTTX_Text),(ULONG)ServerTable->security[i]->Name,
			(TAG_DONE));
	}
	else {
		DisplayBeep(NULL);
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERhullClicked( void )
{
	USER.Hull=GetNumber(Player_EditorGadgets[GD_PLAYERhull]);
	if(USER.Hull%50) {
		USER.Hull-=USER.Hull%50;
		DisplayPLAYER();
	}
	if(!USER.Hull) {
		USER.Cannon=0;
		USER.Ram='N';
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERcannonClicked( void )
{
	USER.Cannon=GetNumber(Player_EditorGadgets[GD_PLAYERcannon]);
	if(USER.Cannon*50>USER.Hull) {
		DisplayBeep(NULL);
		USER.Cannon=USER.Hull/50;
		DisplayPLAYER();
	}
	return(TRUE);
}

int PLAYERramClicked( void )
{
	return(TRUE);
}

int USERidClicked( void )
{
	UpdateUSER();
	strncpy(USER.ID,GetString(User_EditorGadgets[GD_USERid]),sizeof(USER.ID));
	if(USER.ID[0]!='_')
		RPGserver(SERVER_GETUSER,(UBYTE *)&USER);
	else
		memset(&USER,0,sizeof(USER));
	DisplayUSER();
	return(TRUE);
}

int USERnameClicked( void )
{
	return(TRUE);
}

int USERstreetClicked( void )
{
	return(TRUE);
}

int USERcityClicked( void )
{
	return(TRUE);
}

int USERstateClicked( void )
{
	return(TRUE);
}

int USERzipClicked( void )
{
	return(TRUE);
}

int USERvoiceClicked( void )
{
	return(TRUE);
}

int USERdataClicked( void )
{
	return(TRUE);
}

int USERpasswordClicked( void )
{
	strncpy(USER.Password,GetString(User_EditorGadgets[GD_USERpassword]),sizeof(USER.Password));
	strupr(USER.Password);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERpassword],User_EditorWnd,NULL,
		(GTST_String),(ULONG)USER.Password,
		(TAG_DONE));
	return(TRUE);
}

int USERaccessClicked( void )
{
	int i;
	i=GetNumber(User_EditorGadgets[GD_USERaccess]);
	if(i>=0 && i<ServerTable->NumAccess) {
		GT_SetGadgetAttrs(User_EditorGadgets[GD_USERaccessname],User_EditorWnd,NULL,
			(GTTX_Text),(ULONG)ServerTable->access[i]->Name,
			(TAG_DONE));
		GT_SetGadgetAttrs(User_EditorGadgets[GD_USERmaxcalls],User_EditorWnd,NULL,
			(GTNM_Number),(ULONG)ServerTable->access[i]->Calls,
			(TAG_DONE));
	}
	else {
		DisplayBeep(NULL);
		GT_SetGadgetAttrs(User_EditorGadgets[GD_USERaccess],User_EditorWnd,NULL,
			(GTIN_Number),(ULONG)USER.Access,
			(TAG_DONE));
	}
	return(TRUE);
}

int USERcreatedClicked( void )
{
	julian(&USER.CreateDate,GetString(User_EditorGadgets[GD_USERcreated]));
	fdate(dated,USER.CreateDate);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERcreated],User_EditorWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	return(TRUE);
}

int USERexpiredClicked( void )
{
	julian(&USER.ExpireDate,GetString(User_EditorGadgets[GD_USERexpired]));
	fdate(dated,USER.ExpireDate);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERexpired],User_EditorWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	return(TRUE);
}

int USERbirthClicked( void )
{
	julian(&USER.BirthDate,GetString(User_EditorGadgets[GD_USERbirth]));
	fdate(dated,USER.BirthDate);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERbirth],User_EditorWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	return(TRUE);
}

int USERlastonClicked( void )
{
	julian(&USER.LastDate,GetString(User_EditorGadgets[GD_USERlaston]));
	fdate(dated,USER.LastDate);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERlaston],User_EditorWnd,NULL,
		(GTST_String),(ULONG)&dated[4],
		(TAG_DONE));
	return(TRUE);
}

int USERsexClicked( void )
{
	strncpy(&USER.Sex,GetString(User_EditorGadgets[GD_USERsex]),1);
	USER.Sex=toupper(USER.Sex);
	sprintf(dated,"%c",USER.Sex);
	GT_SetGadgetAttrs(User_EditorGadgets[GD_USERsex],User_EditorWnd,NULL,
		(GTST_String),(ULONG)dated,
		(TAG_DONE));
	
	return(TRUE);
}

int USERtotalcallsClicked( void )
{
	return(TRUE);
}

int USERpostsClicked( void )
{
	return(TRUE);
}

int USERcallstodayClicked( void )
{
	return(TRUE);
}

int USERuploadsClicked( void )
{
	return(TRUE);
}

int USERdownloadsClicked( void )
{
	return(TRUE);
}

int USERfileratioClicked( void )
{
	return(TRUE);
}

int USERupbyteClicked( void )
{
	return(TRUE);
}

int USERdownbyteClicked( void )
{
	return(TRUE);
}

int USERbyteratioClicked( void )
{
	return(TRUE);
}

int USERnextClicked( void )
{
	UpdateUSER();
	RPGserver(SERVER_NEXTUSER,(UBYTE *)&USER);
	DisplayUSER();
	return(TRUE);
}

int USERprevClicked( void )
{
	UpdateUSER();
	RPGserver(SERVER_PREVUSER,(UBYTE *)&USER);
	DisplayUSER();
	return(TRUE);
}

int USERdeleteClicked( void )
{
	char filename[81],node[41];
	int i;

	for(i=0; i<999; i++) {
		sprintf(node,"%s.%03d",USER.ID,i);
		strmfp(filename,EMAILpath,node);
		if(remove(filename))
			break;
	}
	strmfp(filename,NOTESpath,USER.ID);
	remove(filename);
	if(RPGserver(SERVER_DELUSER,(UBYTE *)&USER))
		memset(&USER,0,sizeof(USER));
	DisplayUSER();
	return(TRUE);
}

int ReportProfileClicked(void)
{
	FILE *fp;
	int lp=0,pp=0;

	if((fp=fopen("prt:","w"))) {
		memset(&USER,0,sizeof(USER));
		while(RPGserver(SERVER_NEXTUSER,(UBYTE *)&USER)) {
			if(!pp || lp>59) {
				if(pp++)
					fprintf(fp,"\14");
				GetSystemDate(Today);
				julian(&Julian,Today);
				fdate(dated,Julian);
				fprintf(fp,"\nRPGBBS Deluxe User Profile Report as of %s             Page:%3d\n\n\n\n",dated,pp);
				lp=5;
			}
			fdate(dated,USER.BirthDate);
			fprintf(fp,"%-4s %-30s  %-22s  DOB:%s\n",USER.ID,USER.Name,USER.Handle,&dated[4]);
			fdate(dated,USER.CreateDate);
			fprintf(fp,"     %-30s  %-18s  Created:%s\n",USER.Street,ServerTable->access[USER.Access]->Name,&dated[4]);
			fprintf(fp,"     %s, %s  %s\n",USER.City,USER.State,USER.Zip);
			fprintf(fp,"     V:%-16s D:%-16s\n",USER.VoicePhone,USER.DataPhone);
			fprintf(fp,"\n");
			lp+=5;
		}
		if(pp)
			fprintf(fp,"\14");
		fclose(fp);
	}
	return(TRUE);
}

static UWORD ComputeX( UWORD value )
{
	return(( UWORD )((( FontX * value ) + 4 ) / 8 ));
}

static UWORD ComputeY( UWORD value )
{
	return(( UWORD )((( FontY * value ) + 4 ) / 8 ));
}

static void ComputeFont( UWORD width, UWORD height )
{
	Font = &Attr;
	Font->ta_Name = (STRPTR)Scr->RastPort.Font->tf_Message.mn_Node.ln_Name;
//	Font->ta_Name = (STRPTR)"venus.font";
	Font->ta_YSize = FontY = Scr->RastPort.Font->tf_YSize;
//	Font->ta_YSize = FontY = 8;
	FontX = Scr->RastPort.Font->tf_XSize;
//	FontX = 8;

	OffX = Scr->WBorLeft;
	OffY = Scr->RastPort.TxHeight + Scr->WBorTop + 1;

	if ( width && height ) {
		if (( ComputeX( width ) + OffX + Scr->WBorRight ) > Scr->Width )
			goto UseTopaz;
		if (( ComputeY( height ) + OffY + Scr->WBorBottom ) > Scr->Height )
			goto UseTopaz;
	}
	return;

UseTopaz:
	Font->ta_Name = (STRPTR)"topaz.font";
	FontX = FontY = Font->ta_YSize = 8;
}

int SetupScreen( void )
{
	struct Screen *pubscreen;
	struct DrawInfo *pubscreen_drawinfo;

	if ( ! ( pubscreen = LockPubScreen( PubScreenName )))
		if ( ! ( pubscreen = LockPubScreen( NULL )))
			return( 1L );
	if((pubscreen_drawinfo=GetScreenDrawInfo(pubscreen)))
		FreeScreenDrawInfo(pubscreen,pubscreen_drawinfo);
	Scr=pubscreen;
	UnlockPubScreen(NULL,pubscreen);

	ComputeFont( 0, 0 );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		CloseScreen(Scr);
		Scr = NULL;
	}
}

int HandleMainIDCMP( void )
{
	struct IntuiMessage	*m;
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( MainWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&MainMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( MainMsg.Class ) {

			case	IDCMP_CLOSEWINDOW:
				running='Q';
				break;
			case	IDCMP_MENUPICK:
				code=MainMsg.Code;
				menu=MENUNUM(code);
				menuitem=ITEMNUM(code);
				ClearMenuStrip(MainWnd);
				switch(menu) {
					case 0:	//	function
						switch(menuitem) {
							case 0:
								running=SystemSetupClicked();
								break;
							case 1:
								running=TaxmanSetupClicked();
								break;
							case 2:
								running=GangEditorClicked();
								break;
							case 3:
								running=NewUserSetupClicked();
								break;
							case 4:
								running=PlayerEditorClicked();
								break;
							case 5:
								running=UserEditorClicked();
								break;
							case 6:
								running='Q';
								break;
						}
						break;
					case 1:	//	reports
						switch(menuitem) {
							case 0:
								running=ReportProfileClicked();
								break;
						}
						break;
				}
				SetMenuStrip(MainWnd,&function);
				break;
		}
	}
	return( running );
}

int OpenMainWindow( void )
{
	ScreenToFront(Scr);
	if ( ! ( MainWnd = OpenWindowTags( NULL,
				WA_PubScreen, Scr,
				WA_Left, 0, WA_Top, Scr->Height-11,
				WA_Width, Scr->Width, WA_Height, 11,
				WA_MaxWidth, ~0, WA_MaxHeight, ~0,
				WA_MinWidth, Scr->Width, WA_MinHeight, 11,
				WA_Activate, TRUE,
				WA_Backdrop, FALSE,
				WA_Borderless, FALSE,
				WA_CloseGadget, TRUE,
				WA_DepthGadget, TRUE,
				WA_DragBar, TRUE,
				WA_GimmeZeroZero, FALSE,
				WA_IDCMP, IDCMP_CLOSEWINDOW | IDCMP_MENUPICK,
				WA_NoCareRefresh, TRUE,
				WA_SizeGadget, FALSE,
				WA_SizeBBottom, FALSE,
				WA_SmartRefresh, TRUE,
				WA_Title, "RPGBBS Deluxe Sysop Functions",
				TAG_DONE)))
	return( 4L );

	SetMenuStrip(MainWnd,&function);

	return( 0L );
}

void CloseMainWindow( void )
{
	if ( MainWnd        ) {
		CloseWindow( MainWnd );
		MainWnd = NULL;
	}
}

int HandleNew_User_SetupIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( New_User_SetupWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&New_User_SetupMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( New_User_SetupMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( New_User_SetupWnd );
				GT_EndRefresh( New_User_SetupWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = 'Q';
				break;

			case	IDCMP_GADGETUP:
				func = ( void * )(( struct Gadget * )New_User_SetupMsg.IAddress )->UserData;
				running = func();
				break;
		}
	}
	return( running );
}

int OpenNew_User_SetupWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = New_User_SetupLeft, wtop = New_User_SetupTop, ww, wh;

	ComputeFont( New_User_SetupWidth, New_User_SetupHeight );

	ww = ComputeX( New_User_SetupWidth );
	wh = ComputeY( New_User_SetupHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &New_User_SetupGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < New_User_Setup_CNT; lc++ ) {

		CopyMem((char * )&New_User_SetupNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		New_User_SetupGadgets[ lc ] = g = CreateGadgetA((ULONG)New_User_SetupGTypes[ lc ], g, &ng, ( struct TagItem * )&New_User_SetupGTags[ tc ] );

		while( New_User_SetupGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( New_User_SetupWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	STRINGIDCMP|INTEGERIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	New_User_SetupGList,
				WA_Title,	New_User_SetupWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( New_User_SetupWnd, NULL );

	return( 0L );
}

void CloseNew_User_SetupWindow( void )
{
	if ( New_User_SetupWnd        ) {
		CloseWindow( New_User_SetupWnd );
		New_User_SetupWnd = NULL;
	}

	if ( New_User_SetupGList      ) {
		FreeGadgets( New_User_SetupGList );
		New_User_SetupGList = NULL;
	}
}

int HandleTaxman_SetupIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( Taxman_SetupWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&Taxman_SetupMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( Taxman_SetupMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( Taxman_SetupWnd );
				GT_EndRefresh( Taxman_SetupWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = 'Q';
				break;

			case	IDCMP_GADGETUP:
				func = ( void * )(( struct Gadget * )Taxman_SetupMsg.IAddress )->UserData;
				running = func();
				break;
		}
	}
	return( running );
}

int OpenTaxman_SetupWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = Taxman_SetupLeft, wtop = Taxman_SetupTop, ww, wh;

	ComputeFont( Taxman_SetupWidth, Taxman_SetupHeight );

	ww = ComputeX( Taxman_SetupWidth );
	wh = ComputeY( Taxman_SetupHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &Taxman_SetupGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Taxman_Setup_CNT; lc++ ) {

		CopyMem((char * )&Taxman_SetupNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		Taxman_SetupGadgets[ lc ] = g = CreateGadgetA((ULONG)Taxman_SetupGTypes[ lc ], g, &ng, ( struct TagItem * )&Taxman_SetupGTags[ tc ] );

		while( Taxman_SetupGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( Taxman_SetupWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	STRINGIDCMP|INTEGERIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	Taxman_SetupGList,
				WA_Title,	Taxman_SetupWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( Taxman_SetupWnd, NULL );

	return( 0L );
}

void CloseTaxman_SetupWindow( void )
{
	if ( Taxman_SetupWnd        ) {
		CloseWindow( Taxman_SetupWnd );
		Taxman_SetupWnd = NULL;
	}

	if ( Taxman_SetupGList      ) {
		FreeGadgets( Taxman_SetupGList );
		Taxman_SetupGList = NULL;
	}
}

int HandleSystem_SetupIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( System_SetupWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&System_SetupMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( System_SetupMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( System_SetupWnd );
				GT_EndRefresh( System_SetupWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = 'Q';
				break;

			case	IDCMP_GADGETUP:
				func = ( void * )(( struct Gadget * )System_SetupMsg.IAddress )->UserData;
				running = func();
				break;
		}
	}
	return( running );
}

int OpenSystem_SetupWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = System_SetupLeft, wtop = System_SetupTop, ww, wh;

	ComputeFont( System_SetupWidth, System_SetupHeight );

	ww = ComputeX( System_SetupWidth );
	wh = ComputeY( System_SetupHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &System_SetupGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < System_Setup_CNT; lc++ ) {

		CopyMem((char * )&System_SetupNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		System_SetupGadgets[ lc ] = g = CreateGadgetA((ULONG)System_SetupGTypes[ lc ], g, &ng, ( struct TagItem * )&System_SetupGTags[ tc ] );

		while( System_SetupGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( System_SetupWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	STRINGIDCMP|INTEGERIDCMP|TEXTIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	System_SetupGList,
				WA_Title,	System_SetupWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( System_SetupWnd, NULL );

	return( 0L );
}

void CloseSystem_SetupWindow( void )
{
	if ( System_SetupWnd        ) {
		CloseWindow( System_SetupWnd );
		System_SetupWnd = NULL;
	}

	if ( System_SetupGList      ) {
		FreeGadgets( System_SetupGList );
		System_SetupGList = NULL;
	}
}

int HandleGang_EditorIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( Gang_EditorWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&Gang_EditorMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( Gang_EditorMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( Gang_EditorWnd );
				GT_EndRefresh( Gang_EditorWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = 'Q';
				break;

			case	IDCMP_GADGETUP:
				func = ( void * )(( struct Gadget * )Gang_EditorMsg.IAddress )->UserData;
				running = func();
				break;
		}
	}
	return( running );
}

int OpenGang_EditorWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = Gang_EditorLeft, wtop = Gang_EditorTop, ww, wh;

	ComputeFont( Gang_EditorWidth, Gang_EditorHeight );

	ww = ComputeX( Gang_EditorWidth );
	wh = ComputeY( Gang_EditorHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &Gang_EditorGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Gang_Editor_CNT; lc++ ) {

		CopyMem((char * )&Gang_EditorNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		Gang_EditorGadgets[ lc ] = g = CreateGadgetA((ULONG)Gang_EditorGTypes[ lc ], g, &ng, ( struct TagItem * )&Gang_EditorGTags[ tc ] );

		while( Gang_EditorGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( Gang_EditorWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	STRINGIDCMP|BUTTONIDCMP|TEXTIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	Gang_EditorGList,
				WA_Title,	Gang_EditorWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( Gang_EditorWnd, NULL );

	return( 0L );
}

void CloseGang_EditorWindow( void )
{
	if ( Gang_EditorWnd        ) {
		CloseWindow( Gang_EditorWnd );
		Gang_EditorWnd = NULL;
	}

	if ( Gang_EditorGList      ) {
		FreeGadgets( Gang_EditorGList );
		Gang_EditorGList = NULL;
	}
}

int HandlePlayer_EditorIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( Player_EditorWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&Player_EditorMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( Player_EditorMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( Player_EditorWnd );
				GT_EndRefresh( Player_EditorWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = 'Q';
				break;

			case	IDCMP_GADGETUP:
				func = ( void * )(( struct Gadget * )Player_EditorMsg.IAddress )->UserData;
				running = func();
				break;
		}
	}
	return( running );
}

int OpenPlayer_EditorWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = Player_EditorLeft, wtop = Player_EditorTop, ww, wh;

	ComputeFont( Player_EditorWidth, Player_EditorHeight );

	ww = ComputeX( Player_EditorWidth );
	wh = ComputeY( Player_EditorHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &Player_EditorGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Player_Editor_CNT; lc++ ) {

		CopyMem((char * )&Player_EditorNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		Player_EditorGadgets[ lc ] = g = CreateGadgetA((ULONG)Player_EditorGTypes[ lc ], g, &ng, ( struct TagItem * )&Player_EditorGTags[ tc ] );

		while( Player_EditorGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( Player_EditorWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	BUTTONIDCMP|TEXTIDCMP|CHECKBOXIDCMP|STRINGIDCMP|INTEGERIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	Player_EditorGList,
				WA_Title,	Player_EditorWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( Player_EditorWnd, NULL );

	return( 0L );
}

void ClosePlayer_EditorWindow( void )
{
	if ( Player_EditorWnd        ) {
		CloseWindow( Player_EditorWnd );
		Player_EditorWnd = NULL;
	}

	if ( Player_EditorGList      ) {
		FreeGadgets( Player_EditorGList );
		Player_EditorGList = NULL;
	}
}

int HandleUser_EditorIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( User_EditorWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&User_EditorMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( User_EditorMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( User_EditorWnd );
				GT_EndRefresh( User_EditorWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = 'Q';
				break;

			case	IDCMP_GADGETUP:
				func = ( void * )(( struct Gadget * )User_EditorMsg.IAddress )->UserData;
				running = func();
				break;
		}
	}
	return( running );
}

int OpenUser_EditorWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = User_EditorLeft, wtop = User_EditorTop, ww, wh;

	ComputeFont( User_EditorWidth, User_EditorHeight );

	ww = ComputeX( User_EditorWidth );
	wh = ComputeY( User_EditorHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &User_EditorGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < User_Editor_CNT; lc++ ) {

		CopyMem((char * )&User_EditorNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		User_EditorGadgets[ lc ] = g = CreateGadgetA((ULONG)User_EditorGTypes[ lc ], g, &ng, ( struct TagItem * )&User_EditorGTags[ tc ] );

		while( User_EditorGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( User_EditorWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	STRINGIDCMP|TEXTIDCMP|INTEGERIDCMP|BUTTONIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	User_EditorGList,
				WA_Title,	User_EditorWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( User_EditorWnd, NULL );

	return( 0L );
}

void CloseUser_EditorWindow( void )
{
	if ( User_EditorWnd        ) {
		CloseWindow( User_EditorWnd );
		User_EditorWnd = NULL;
	}

	if ( User_EditorGList      ) {
		FreeGadgets( User_EditorGList );
		User_EditorGList = NULL;
	}
}

void finputs(char *str,int n,FILE *file)
{
	if(!fgets(str,n,file))
		memset(str,0,n);
	if(str[strlen(str)-1]=='\n')
		str[strlen(str)-1]='\0';
}

void main(int argc,char **args)
{
	FILE *fp;

	if(!(RPGBase=OpenLibrary("rpgbbs.library",0L)))
		exit(1);

	if(!(RPGreply=(struct MsgPort *)CreatePort(NULL,0)))
		exit(2);
	server.message.mn_Node.ln_Type=NT_MESSAGE;
	server.message.mn_Length=sizeof(struct RPGserver);
	server.message.mn_ReplyPort=RPGreply;
	Forbid();
	RPGport=(struct MsgPort *)FindPort("RPGBBS Deluxe Server");
	Permit();
	if(!RPGport)
		exit(3);
	if(!RPGserver(SERVER_CONNECT,NULL))
		exit(4);

	if((fp=fopen("RPGBBS.paths","r"))) {
		finputs(EMAILpath,sizeof(EMAILpath),fp);
		finputs(MSGpath,sizeof(MSGpath),fp);
		finputs(NOTESpath,sizeof(NOTESpath),fp);
		fclose(fp);
	}

	if(!SetupScreen()) {
		MainTop=(Scr->Height-MainHeight)/2;
		MainLeft=(Scr->Width-MainWidth)/2;
		System_SetupTop=(Scr->Height-System_SetupHeight)/2;
		System_SetupLeft=(Scr->Width-System_SetupWidth)/2;
		Taxman_SetupTop=(Scr->Height-Taxman_SetupHeight)/2;
		Taxman_SetupLeft=(Scr->Width-Taxman_SetupWidth)/2;
		Gang_EditorTop=(Scr->Height-Gang_EditorHeight)/2;
		Gang_EditorLeft=(Scr->Width-Gang_EditorWidth)/2;
		New_User_SetupTop=(Scr->Height-New_User_SetupHeight)/2;
		New_User_SetupLeft=(Scr->Width-New_User_SetupWidth)/2;
		Player_EditorTop=(Scr->Height-Player_EditorHeight)/2;
		Player_EditorLeft=(Scr->Width-Player_EditorWidth)/2;
		User_EditorTop=(Scr->Height-User_EditorHeight)/2;
		User_EditorLeft=(Scr->Width-User_EditorWidth)/2;
		if(!OpenMainWindow()) {
			FOREVER {
				Wait(1L<<MainWnd->UserPort->mp_SigBit);
				if(HandleMainIDCMP()=='Q')
					break;
			}
			CloseMainWindow();
		}
		CloseDownScreen();
	}

	RPGserver(SERVER_DISCONNECT,NULL);
	DeletePort(RPGreply);
	CloseLibrary(RPGBase);
}
