/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Robert Hurst
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_New                                 0
#define GD_Delete                              1
#define GD_GenKey                              2
#define GD_License                             3
#define GD_Name                                4
#define GD_Addr1                               5
#define GD_Addr2                               6
#define GD_Addr3                               7
#define GD_Key                                 8

#define GDX_New                                0
#define GDX_Delete                             1
#define GDX_GenKey                             2
#define GDX_License                            3
#define GDX_Name                               4
#define GDX_Addr1                              5
#define GDX_Addr2                              6
#define GDX_Addr3                              7
#define GDX_Key                                8

#define Main_CNT 9

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct IntuiMessage   MainMsg;

extern int NewClicked( void );
extern int DeleteClicked( void );
extern int GenKeyClicked( void );
extern int LicenseClicked( void );
extern int NameClicked( void );
extern int Addr1Clicked( void );
extern int Addr2Clicked( void );
extern int Addr3Clicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleMainIDCMP( void );
extern int MainCloseWindow();
extern int OpenMainWindow( void );
extern void CloseMainWindow( void );
