#pragma libcall DesTrackerBase Dispatch 1E 0
#pragma libcall DesTrackerBase OwnPlayer 24 0
#pragma libcall DesTrackerBase DisownPlayer 2A 0
#pragma libcall DesTrackerBase SetModulePath 30 801
#pragma libcall DesTrackerBase SetFilter 36 001
#pragma libcall DesTrackerBase SetChannelEnable 3C 001
#pragma libcall DesTrackerBase SetStartPosition 42 1002
#pragma libcall DesTrackerBase SetEndPosition 48 1002
#pragma libcall DesTrackerBase SetIterations 4E 001
#pragma libcall DesTrackerBase PausePlaySeq 54 0
#pragma libcall DesTrackerBase ContinuePlaySeq 5A 0
#pragma libcall DesTrackerBase SetGlobalVolume 60 001
#pragma libcall DesTrackerBase SetInstVolume 66 1002
#pragma libcall DesTrackerBase SetDefaultTempo 6C 001
#pragma libcall DesTrackerBase SetGlobalTempo 72 001
#pragma libcall DesTrackerBase SetFineTempo 78 001
#pragma libcall DesTrackerBase FadeGlobalVolume 7E 001
#pragma libcall DesTrackerBase SetVolumeFadeRate 84 001
#pragma libcall DesTrackerBase LoadModule 8A 801
#pragma libcall DesTrackerBase UnloadModule 90 0
#pragma libcall DesTrackerBase BeginPlaySeq 96 0
#pragma libcall DesTrackerBase ApplyGlobalTempo 9C 0
#pragma libcall DesTrackerBase RetitleModule A2 801
#pragma libcall DesTrackerBase SetCurPosition A8 1002
#pragma libcall DesTrackerBase SaveModule AE 801
#pragma libcall DesTrackerBase SetSaveFormat B4 001
#pragma libcall DesTrackerBase VerifyModule BA 801
#pragma libcall DesTrackerBase SetTimingMode C0 001
#pragma libcall DesTrackerBase SetAutoTiming C6 001
#pragma libcall DesTrackerBase SetLoopIntent CC 001
#pragma libcall DesTrackerBase ResetDefaults D2 0
#pragma libcall DesTrackerBase SetTempoInt D8 001
#pragma libcall DesTrackerBase AddStatusSignal DE 1002
#pragma libcall DesTrackerBase RemStatusSignal E4 001
#pragma libcall DesTrackerBase StopPlaySeq EA 0
#pragma libcall DesTrackerBase InstallModule F0 801
#pragma libcall DesTrackerBase CalcElapsedTime F6 801
#pragma libcall DesTrackerBase SetTemporalStart FC 001
#pragma libcall DesTrackerBase SetTemporalEnd 102 001
#pragma libcall DesTrackerBase SetTemporalPos 108 001
#pragma libcall DesTrackerBase CalcVolFadeTime 10E 21003
